GLOBAL_LIST_INIT(bitfields, generate_bitfields())

/// Specifies a bitfield for smarter debugging
/datum/bitfield
	/// The variable name that contains the bitfield
	var/variable

	/// An associative list of the readable flag and its true value
	var/list/flags

/// Turns /datum/bitfield subtypes into a list for use in debugging
/proc/generate_bitfields()
	var/list/bitfields = list()
	for (var/_bitfield in subtypesof(/datum/bitfield))
		var/datum/bitfield/bitfield = new _bitfield
		bitfields[bitfield.variable] = bitfield.flags
	return bitfields

/// Returns an associative list of bitflag name -> number for all valid bitflags in the passed in field
/proc/get_valid_bitflags(var_name)
	return GLOB.bitfields[var_name] || list()

/proc/get_random_bitflag(var_name)
	var/list/flags = get_valid_bitflags(var_name)
	if(!length(flags))
		return
	var/name = pick(flags)
	return flags[name]


DEFINE_BITFIELD(admin_flags, list(
	"ADMIN" = R_ADMIN,
	"MENTOR" = R_MENTOR,
	"BAN" = R_BAN,
	"ASAY" = R_ASAY,
	"ADMINTICKET" = R_ADMINTICKET,
	"FUN" = R_FUN,
	"SERVER" = R_SERVER,
	"DEBUG" = R_DEBUG,
	"PERMISSIONS" = R_PERMISSIONS,
	"COLOR" = R_COLOR,
	"VAREDIT" = R_VAREDIT,
	"SOUND" = R_SOUND,
	"SPAWN" = R_SPAWN,
	"DBRANKS" = R_DBRANKS,
	"RUNTIME" = R_RUNTIME,
	"LOG" = R_LOG,
	"POLLS" = R_POLLS
))

DEFINE_BITFIELD(machine_stat, list(
	"BROKEN" = BROKEN,
	"NOPOWER" = NOPOWER,
	"POWEROFF" = POWEROFF,
	"MAINT" = MAINT,
	"EMPED" = EMPED,
	"PANEL_OPEN" = PANEL_OPEN,
	"DISABLED" = DISABLED,
	"KNOCKED_DOWN" = KNOCKED_DOWN,
	"MACHINE_DO_NOT_PROCESS" = MACHINE_DO_NOT_PROCESS
))

DEFINE_BITFIELD(gun_features_flags, list(
	"GUN_CAN_POINTBLANK" = GUN_CAN_POINTBLANK,
	"GUN_UNUSUAL_DESIGN" = GUN_UNUSUAL_DESIGN,
	"GUN_AMMO_COUNTER" = GUN_AMMO_COUNTER,
	"GUN_WIELDED_FIRING_ONLY" = GUN_WIELDED_FIRING_ONLY,
	"GUN_ALLOW_SYNTHETIC" = GUN_ALLOW_SYNTHETIC,
	"GUN_WIELDED_STABLE_FIRING_ONLY" = GUN_WIELDED_STABLE_FIRING_ONLY,
	"GUN_IFF" = GUN_IFF,
	"GUN_DEPLOYED_FIRE_ONLY" = GUN_DEPLOYED_FIRE_ONLY,
	"GUN_IS_ATTACHMENT" = GUN_IS_ATTACHMENT,
	"GUN_ATTACHMENT_FIRE_ONLY" = GUN_ATTACHMENT_FIRE_ONLY,
	"GUN_ENERGY" = GUN_ENERGY,
	"GUN_AMMO_COUNT_BY_PERCENTAGE" = GUN_AMMO_COUNT_BY_PERCENTAGE,
	"GUN_AMMO_COUNT_BY_SHOTS_REMAINING" = GUN_AMMO_COUNT_BY_SHOTS_REMAINING,
	"GUN_NO_PITCH_SHIFT_NEAR_EMPTY" = GUN_NO_PITCH_SHIFT_NEAR_EMPTY,
	"GUN_SHOWS_AMMO_REMAINING" = GUN_SHOWS_AMMO_REMAINING,
	"GUN_SHOWS_LOADED" = GUN_SHOWS_LOADED,
	"GUN_SMOKE_PARTICLES" = GUN_SMOKE_PARTICLES
))

DEFINE_BITFIELD(flamer_features_flags, list(
	"FLAMER_IS_LIT" = FLAMER_IS_LIT,
	"FLAMER_NO_LIT_OVERLAY" = FLAMER_NO_LIT_OVERLAY,
	"FLAMER_USES_GUN_FLAMES" = FLAMER_USES_GUN_FLAMES
))

DEFINE_BITFIELD(magazine_flags, list(
	"MAGAZINE_REFILLABLE" = MAGAZINE_REFILLABLE,
	"MAGAZINE_HANDFUL" = MAGAZINE_HANDFUL,
	"MAGAZINE_WORN" = MAGAZINE_WORN,
	"MAGAZINE_REFUND_IN_CHAMBER" = MAGAZINE_REFUND_IN_CHAMBER
))

DEFINE_BITFIELD(reciever_flags, list(
	"AMMO_RECIEVER_REQUIRES_UNIQUE_ACTION" = AMMO_RECIEVER_REQUIRES_UNIQUE_ACTION,
	"AMMO_RECIEVER_UNIQUE_ACTION_LOCKS" = AMMO_RECIEVER_UNIQUE_ACTION_LOCKS,
	"AMMO_RECIEVER_MAGAZINES" = AMMO_RECIEVER_MAGAZINES,
	"AMMO_RECIEVER_AUTO_EJECT" = AMMO_RECIEVER_AUTO_EJECT,
	"AMMO_RECIEVER_HANDFULS" = AMMO_RECIEVER_HANDFULS,
	"AMMO_RECIEVER_TOGGLES_OPEN" = AMMO_RECIEVER_TOGGLES_OPEN,
	"AMMO_RECIEVER_TOGGLES_OPEN_EJECTS" = AMMO_RECIEVER_TOGGLES_OPEN_EJECTS,
	"AMMO_RECIEVER_CLOSED" = AMMO_RECIEVER_CLOSED,
	"AMMO_RECIEVER_ROTATES_CHAMBER" = AMMO_RECIEVER_ROTATES_CHAMBER,
	"AMMO_RECIEVER_DO_NOT_EJECT_HANDFULS" = AMMO_RECIEVER_DO_NOT_EJECT_HANDFULS,
	"AMMO_RECIEVER_DO_NOT_EMPTY_ROUNDS_AFTER_FIRE" = AMMO_RECIEVER_DO_NOT_EMPTY_ROUNDS_AFTER_FIRE,
	"AMMO_RECIEVER_CYCLE_ONLY_BEFORE_FIRE" = AMMO_RECIEVER_CYCLE_ONLY_BEFORE_FIRE,
	"AMMO_RECIEVER_AUTO_EJECT_LOCKED" = AMMO_RECIEVER_AUTO_EJECT_LOCKED
))

DEFINE_BITFIELD(be_special, list(
	"BE_ALIEN" = BE_ALIEN,
	"BE_QUEEN" = BE_QUEEN,
	"BE_SURVIVOR" = BE_SURVIVOR,
	"BE_DEATHMATCH" = BE_DEATHMATCH,
	"BE_SQUAD_STRICT" = BE_SQUAD_STRICT,
	"BE_ALIEN_UNREVIVABLE" = BE_ALIEN_UNREVIVABLE,
	"BE_SSD_RANDOM_NAME" = BE_SSD_RANDOM_NAME
))

DEFINE_BITFIELD(status_toggle_flags, list(
	"HIVE_STATUS_SHOW_EMPTY" = HIVE_STATUS_SHOW_EMPTY,
	"HIVE_STATUS_COMPACT_MODE" = HIVE_STATUS_COMPACT_MODE,
	"HIVE_STATUS_SHOW_GENERAL" = HIVE_STATUS_SHOW_GENERAL,
	"HIVE_STATUS_SHOW_POPULATION" = HIVE_STATUS_SHOW_POPULATION,
	"HIVE_STATUS_SHOW_XENO_LIST" = HIVE_STATUS_SHOW_XENO_LIST,
	"HIVE_STATUS_SHOW_STRUCTURES" = HIVE_STATUS_SHOW_STRUCTURES
))

DEFINE_BITFIELD(atom_flags, list(
	"UNUSED_RESERVATION_TURF_1" = UNUSED_RESERVATION_TURF_1,
	"AI_BLOCKED" = AI_BLOCKED,
	"NOINTERACT" = NOINTERACT,
	"CONDUCT" = CONDUCT,
	"ON_BORDER" = ON_BORDER,
	"NOBLOODY" = NOBLOODY,
	"DIRLOCK" = DIRLOCK,
	"INITIALIZED" = INITIALIZED,
	"NODECONSTRUCT" = NODECONSTRUCT,
	"PREVENT_CLICK_UNDER" = PREVENT_CLICK_UNDER,
	"CRITICAL_ATOM" = CRITICAL_ATOM,
	"PREVENT_CONTENTS_EXPLOSION" = PREVENT_CONTENTS_EXPLOSION,
	"ADMIN_SPAWNED" = ADMIN_SPAWNED,
	"BUMP_ATTACKABLE" = BUMP_ATTACKABLE,
	"SHUTTLE_IMMUNE" = SHUTTLE_IMMUNE,
	"HTML_USE_INITAL_ICON_1" = HTML_USE_INITAL_ICON_1
))

DEFINE_BITFIELD(area_flags, list(
	"DISALLOW_WEEDING" = DISALLOW_WEEDING,
	"NEAR_FOB" = NEAR_FOB,
	"NO_DROPPOD" = NO_DROPPOD,
	"OB_CAS_IMMUNE" = OB_CAS_IMMUNE,
	"MARINE_BASE" = MARINE_BASE,
	"ALWAYS_RADIO" = ALWAYS_RADIO,
	"NO_CONSTRUCTION" = NO_CONSTRUCTION,
	"CANNOT_NUKE" = CANNOT_NUKE
))

DEFINE_BITFIELD(turf_flags, list(
	"UNUSED_RESERVATION_TURF" = UNUSED_RESERVATION_TURF,
	"RESERVATION_TURF" = RESERVATION_TURF
))

DEFINE_BITFIELD(obj_flags, list(
	"IN_USE" = IN_USE,
	"CAN_BE_HIT" = CAN_BE_HIT,
	"PROJ_IGNORE_DENSITY" = PROJ_IGNORE_DENSITY,
	"LIGHT_CAN_BE_SHUT" = LIGHT_CAN_BE_SHUT,
	"BLOCKS_CONSTRUCTION" = BLOCKS_CONSTRUCTION,
	"BLOCKS_CONSTRUCTION_DIR" = BLOCKS_CONSTRUCTION_DIR,
	"IGNORE_DENSITY" = IGNORE_DENSITY,
	"BLOCK_Z_OUT_DOWN" = BLOCK_Z_OUT_DOWN,
	"BLOCK_Z_OUT_UP" = BLOCK_Z_OUT_UP,
	"BLOCK_Z_IN_DOWN" = BLOCK_Z_IN_DOWN,
	"BLOCK_Z_IN_UP" = BLOCK_Z_IN_UP
))

DEFINE_BITFIELD(appearance_flags, list(
	"LONG_GLIDE" = LONG_GLIDE,
	"RESET_COLOR" = RESET_COLOR,
	"RESET_ALPHA" = RESET_ALPHA,
	"RESET_TRANSFORM" = RESET_TRANSFORM,
	"NO_CLIENT_COLOR" = NO_CLIENT_COLOR,
	"KEEP_TOGETHER" = KEEP_TOGETHER,
	"KEEP_APART" = KEEP_APART,
	"PLANE_MASTER" = PLANE_MASTER,
	"TILE_BOUND" = TILE_BOUND,
	"PIXEL_SCALE" = PIXEL_SCALE,
	"PASS_MOUSE" = PASS_MOUSE,
	"TILE_MOVER" = TILE_MOVER
))

DEFINE_BITFIELD(datum_flags, list(
	"DF_USE_TAG" = DF_USE_TAG,
	"DF_VAR_EDITED" = DF_VAR_EDITED,
	"DF_ISPROCESSING" = DF_ISPROCESSING
))

DEFINE_BITFIELD(allow_pass_flags, list(
	"PASS_LOW_STRUCTURE" = PASS_LOW_STRUCTURE,
	"PASS_GLASS" = PASS_GLASS,
	"PASS_GRILLE" = PASS_GRILLE,
	"PASS_MOB" = PASS_MOB,
	"PASS_DEFENSIVE_STRUCTURE" = PASS_DEFENSIVE_STRUCTURE,
	"PASS_FIRE" = PASS_FIRE,
	"PASS_XENO" = PASS_XENO,
	"PASS_THROW" = PASS_THROW,
	"PASS_PROJECTILE" = PASS_PROJECTILE,
	"PASS_AIR" = PASS_AIR,
	"PASS_WALKOVER" = PASS_WALKOVER,
	"PASS_TANK" = PASS_TANK
))

DEFINE_BITFIELD(pass_flags, list(
	"PASS_LOW_STRUCTURE" = PASS_LOW_STRUCTURE,
	"PASS_GLASS" = PASS_GLASS,
	"PASS_GRILLE" = PASS_GRILLE,
	"PASS_MOB" = PASS_MOB,
	"PASS_DEFENSIVE_STRUCTURE" = PASS_DEFENSIVE_STRUCTURE,
	"PASS_FIRE" = PASS_FIRE,
	"PASS_XENO" = PASS_XENO,
	"PASS_THROW" = PASS_THROW,
	"PASS_PROJECTILE" = PASS_PROJECTILE,
	"PASS_AIR" = PASS_AIR,
	"PASS_WALKOVER" = PASS_WALKOVER,
	"PASS_TANK" = PASS_TANK
))

DEFINE_BITFIELD(status_flags, list(
	"CANSTUN" = CANSTUN,
	"CANKNOCKDOWN" = CANKNOCKDOWN,
	"CANKNOCKOUT" = CANKNOCKOUT,
	"CANPUSH" = CANPUSH,
	"GODMODE" = GODMODE,
	"FAKEDEATH" = FAKEDEATH,
	"DISFIGURED" = DISFIGURED,
	"XENO_HOST" = XENO_HOST,
	"TK_USER" = TK_USER,
	"CANUNCONSCIOUS" = CANUNCONSCIOUS,
	"CANCONFUSE" = CANCONFUSE,
	"INCORPOREAL" = INCORPOREAL
))

DEFINE_BITFIELD(muted, list(
	"MUTE_IC" = MUTE_IC,
	"MUTE_OOC" = MUTE_OOC,
	"MUTE_PRAY" = MUTE_PRAY,
	"MUTE_ADMINHELP" = MUTE_ADMINHELP,
	"MUTE_DEADCHAT" = MUTE_DEADCHAT,
	"MUTE_LOOC" = MUTE_LOOC,
	"MUTE_TTS" = MUTE_TTS
))

DEFINE_BITFIELD(piping_layer, list(
	"PIPING_ALL_LAYER" = PIPING_ALL_LAYER,
	"PIPING_ONE_PER_TURF" = PIPING_ONE_PER_TURF,
	"PIPING_DEFAULT_LAYER_ONLY" = PIPING_DEFAULT_LAYER_ONLY,
	"PIPING_CARDINAL_AUTONORMALIZE" = PIPING_CARDINAL_AUTONORMALIZE
))

DEFINE_BITFIELD(inv_hide_flags, list(
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDESHOES" = HIDESHOES,
	"HIDEMASK" = HIDEMASK,
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDELOWHAIR" = HIDELOWHAIR,
	"HIDETOPHAIR" = HIDETOPHAIR,
	"HIDEALLHAIR" = HIDEALLHAIR,
	"HIDEFACE" = HIDEFACE,
	"HIDE_EXCESS_HAIR" = HIDE_EXCESS_HAIR
))

DEFINE_BITFIELD(inventory_flags, list(
	"NOSLIPPING" = NOSLIPPING,
	"COVEREYES" = COVEREYES,
	"COVERMOUTH" = COVERMOUTH,
	"BLOCKGASEFFECT" = BLOCKGASEFFECT,
	"BLOCKSHARPOBJ" = BLOCKSHARPOBJ,
	"NOPRESSUREDMAGE" = NOPRESSUREDMAGE,
	"NOQUICKEQUIP" = NOQUICKEQUIP
))

DEFINE_BITFIELD(armor_features_flags, list(
	"ARMOR_SQUAD_OVERLAY" = ARMOR_SQUAD_OVERLAY,
	"ARMOR_LAMP_OVERLAY" = ARMOR_LAMP_OVERLAY,
	"ARMOR_LAMP_ON" = ARMOR_LAMP_ON,
	"ARMOR_IS_REINFORCED" = ARMOR_IS_REINFORCED,
	"ARMOR_NO_DECAP" = ARMOR_NO_DECAP,
	"ARMOR_FIRE_RESISTANT" = ARMOR_FIRE_RESISTANT
))

DEFINE_BITFIELD(marine_helmet_flags, list(
	"HELMET_SQUAD_OVERLAY" = HELMET_SQUAD_OVERLAY,
	"HELMET_GARB_OVERLAY" = HELMET_GARB_OVERLAY,
	"HELMET_STORE_GARB" = HELMET_STORE_GARB,
	"HELMET_IS_DAMAGED" = HELMET_IS_DAMAGED
))

DEFINE_BITFIELD(equip_slot_flags, list(
	"ITEM_SLOT_OCLOTHING" = ITEM_SLOT_OCLOTHING,
	"ITEM_SLOT_ICLOTHING" = ITEM_SLOT_ICLOTHING,
	"ITEM_SLOT_GLOVES" = ITEM_SLOT_GLOVES,
	"ITEM_SLOT_EYES" = ITEM_SLOT_EYES,
	"ITEM_SLOT_EARS" = ITEM_SLOT_EARS,
	"ITEM_SLOT_MASK" = ITEM_SLOT_MASK,
	"ITEM_SLOT_HEAD" = ITEM_SLOT_HEAD,
	"ITEM_SLOT_FEET" = ITEM_SLOT_FEET,
	"ITEM_SLOT_ID" = ITEM_SLOT_ID,
	"ITEM_SLOT_BELT" = ITEM_SLOT_BELT,
	"ITEM_SLOT_BACK" = ITEM_SLOT_BACK,
	"ITEM_SLOT_R_POCKET" = ITEM_SLOT_R_POCKET,
	"ITEM_SLOT_L_POCKET" = ITEM_SLOT_L_POCKET,
	"ITEM_SLOT_SUITSTORE" = ITEM_SLOT_SUITSTORE,
	"ITEM_SLOT_HANDCUFF" = ITEM_SLOT_HANDCUFF,
	"ITEM_SLOT_L_HAND" = ITEM_SLOT_L_HAND,
	"ITEM_SLOT_R_HAND" = ITEM_SLOT_R_HAND
))

DEFINE_BITFIELD(thermal_protection_flags, list(
	"HEAD" = HEAD,
	"FACE" = FACE,
	"EYES" = EYES,
	"CHEST" = CHEST,
	"GROIN" = GROIN,
	"LEG_LEFT" = LEG_LEFT,
	"LEG_RIGHT" = LEG_RIGHT,
	"FOOT_LEFT" = FOOT_LEFT,
	"FOOT_RIGHT" = FOOT_RIGHT,
	"ARM_LEFT" = ARM_LEFT,
	"ARM_RIGHT" = ARM_RIGHT,
	"HAND_LEFT" = HAND_LEFT,
	"HAND_RIGHT" = HAND_RIGHT
))

DEFINE_BITFIELD(armor_protection_flags, list(
	"HEAD" = HEAD,
	"FACE" = FACE,
	"EYES" = EYES,
	"CHEST" = CHEST,
	"GROIN" = GROIN,
	"LEG_LEFT" = LEG_LEFT,
	"LEG_RIGHT" = LEG_RIGHT,
	"FOOT_LEFT" = FOOT_LEFT,
	"FOOT_RIGHT" = FOOT_RIGHT,
	"ARM_LEFT" = ARM_LEFT,
	"ARM_RIGHT" = ARM_RIGHT,
	"HAND_LEFT" = HAND_LEFT,
	"HAND_RIGHT" = HAND_RIGHT
))

DEFINE_BITFIELD(cold_protection_flags, list(
	"HEAD" = HEAD,
	"FACE" = FACE,
	"EYES" = EYES,
	"CHEST" = CHEST,
	"GROIN" = GROIN,
	"LEG_LEFT" = LEG_LEFT,
	"LEG_RIGHT" = LEG_RIGHT,
	"FOOT_LEFT" = FOOT_LEFT,
	"FOOT_RIGHT" = FOOT_RIGHT,
	"ARM_LEFT" = ARM_LEFT,
	"ARM_RIGHT" = ARM_RIGHT,
	"HAND_LEFT" = HAND_LEFT,
	"HAND_RIGHT" = HAND_RIGHT
))

DEFINE_BITFIELD(heat_protection_flags, list(
	"HEAD" = HEAD,
	"FACE" = FACE,
	"EYES" = EYES,
	"CHEST" = CHEST,
	"GROIN" = GROIN,
	"LEG_LEFT" = LEG_LEFT,
	"LEG_RIGHT" = LEG_RIGHT,
	"FOOT_LEFT" = FOOT_LEFT,
	"FOOT_RIGHT" = FOOT_RIGHT,
	"ARM_LEFT" = ARM_LEFT,
	"ARM_RIGHT" = ARM_RIGHT,
	"HAND_LEFT" = HAND_LEFT,
	"HAND_RIGHT" = HAND_RIGHT
))

DEFINE_BITFIELD(update_overlay, list(
	"UPOVERLAY_OPERATING" = UPOVERLAY_OPERATING,
	"UPOVERLAY_LOCKED" = UPOVERLAY_LOCKED
))

DEFINE_BITFIELD(update_state, list(
	"UPSTATE_BROKE" = UPSTATE_BROKE,
	"UPSTATE_MAINT" = UPSTATE_MAINT,
	"UPSTATE_WIREEXP" = UPSTATE_WIREEXP
))

DEFINE_BITFIELD(apcwires, list(
	"APC_WIRE_IDSCAN" = APC_WIRE_IDSCAN,
	"APC_WIRE_MAIN_POWER1" = APC_WIRE_MAIN_POWER1,
	"APC_WIRE_MAIN_POWER2" = APC_WIRE_MAIN_POWER2,
	"APC_WIRE_AI_CONTROL" = APC_WIRE_AI_CONTROL
))

DEFINE_BITFIELD(specialfunctions, list(
	"OPEN" = OPEN,
	"IDSCAN" = IDSCAN,
	"BOLTS" = BOLTS,
	"SHOCK" = SHOCK,
	"SAFE" = SAFE
))

DEFINE_BITFIELD(reagent_flags, list(
	"INJECTABLE" = INJECTABLE,
	"DRAWABLE" = DRAWABLE,
	"REFILLABLE" = REFILLABLE,
	"DRAINABLE" = DRAINABLE,
	"TRANSPARENT" = TRANSPARENT,
	"AMOUNT_VISIBLE" = AMOUNT_VISIBLE,
	"AMOUNT_SKILLCHECK" = AMOUNT_SKILLCHECK,
	"AMOUNT_ESTIMEE" = AMOUNT_ESTIMEE,
	"NO_REACT" = NO_REACT
))

DEFINE_BITFIELD(trait_flags, list(
	"TACHYCARDIC" = TACHYCARDIC,
	"BRADYCARDICS" = BRADYCARDICS,
	"HEARTSTOPPER" = HEARTSTOPPER,
	"CHEARTSTOPPER" = CHEARTSTOPPER
))

DEFINE_BITFIELD(limb_status, list(
	"LIMB_BLEEDING" = LIMB_BLEEDING,
	"LIMB_BROKEN" = LIMB_BROKEN,
	"LIMB_DESTROYED" = LIMB_DESTROYED,
	"LIMB_ROBOT" = LIMB_ROBOT,
	"LIMB_SPLINTED" = LIMB_SPLINTED,
	"LIMB_NECROTIZED" = LIMB_NECROTIZED,
	"LIMB_AMPUTATED" = LIMB_AMPUTATED,
	"LIMB_REPAIRED" = LIMB_REPAIRED,
	"LIMB_STABILIZED" = LIMB_STABILIZED,
	"LIMB_BIOTIC" = LIMB_BIOTIC
))

DEFINE_BITFIELD(caste_flags, list(
	"CASTE_FIRE_IMMUNE" = CASTE_FIRE_IMMUNE,
	"CASTE_EVOLUTION_ALLOWED" = CASTE_EVOLUTION_ALLOWED,
	"CASTE_IS_INTELLIGENT" = CASTE_IS_INTELLIGENT,
	"CASTE_DO_NOT_ALERT_LOW_LIFE" = CASTE_DO_NOT_ALERT_LOW_LIFE,
	"CASTE_HIDE_IN_STATUS" = CASTE_HIDE_IN_STATUS,
	"CASTE_QUICK_HEAL_STANDING" = CASTE_QUICK_HEAL_STANDING,
	"CASTE_INNATE_PLASMA_REGEN" = CASTE_INNATE_PLASMA_REGEN,
	"CASTE_ACID_BLOOD" = CASTE_ACID_BLOOD,
	"CASTE_IS_BUILDER" = CASTE_IS_BUILDER,
	"CASTE_IS_A_MINION" = CASTE_IS_A_MINION,
	"CASTE_PLASMADRAIN_IMMUNE" = CASTE_PLASMADRAIN_IMMUNE,
	"CASTE_NOT_IN_BIOSCAN" = CASTE_NOT_IN_BIOSCAN,
	"CASTE_DO_NOT_ANNOUNCE_DEATH" = CASTE_DO_NOT_ANNOUNCE_DEATH,
	"CASTE_STAGGER_RESISTANT" = CASTE_STAGGER_RESISTANT,
	"CASTE_EXCLUDE_STRAINS" = CASTE_EXCLUDE_STRAINS,
	"CASTE_MUTATIONS_ALLOWED" = CASTE_MUTATIONS_ALLOWED,
))

DEFINE_BITFIELD(can_flags, list(
	"CASTE_CAN_HOLD_FACEHUGGERS" = CASTE_CAN_HOLD_FACEHUGGERS,
	"CASTE_CAN_BE_GIVEN_PLASMA" = CASTE_CAN_BE_GIVEN_PLASMA,
	"CASTE_CAN_BE_LEADER" = CASTE_CAN_BE_LEADER,
	"CASTE_CAN_HEAL_WITHOUT_QUEEN" = CASTE_CAN_HEAL_WITHOUT_QUEEN,
	"CASTE_CAN_CORRUPT_GENERATOR" = CASTE_CAN_CORRUPT_GENERATOR,
	"CASTE_CAN_RIDE_CRUSHER" = CASTE_CAN_RIDE_CRUSHER
))

DEFINE_BITFIELD(species_flags, list(
	"NO_BLOOD" = NO_BLOOD,
	"NO_BREATHE" = NO_BREATHE,
	"NO_SCAN" = NO_SCAN,
	"NO_PAIN" = NO_PAIN,
	"NO_OVERDOSE" = NO_OVERDOSE,
	"NO_POISON" = NO_POISON,
	"NO_CHEM_METABOLIZATION" = NO_CHEM_METABOLIZATION,
	"HAS_SKIN_COLOR" = HAS_SKIN_COLOR,
	"HAS_LIPS" = HAS_LIPS,
	"HAS_UNDERWEAR" = HAS_UNDERWEAR,
	"HAS_NO_HAIR" = HAS_NO_HAIR,
	"IS_SYNTHETIC" = IS_SYNTHETIC,
	"NO_STAMINA" = NO_STAMINA,
	"DETACHABLE_HEAD" = DETACHABLE_HEAD,
	"USES_ALIEN_WEAPONS" = USES_ALIEN_WEAPONS,
	"NO_DAMAGE_OVERLAY" = NO_DAMAGE_OVERLAY,
	"HEALTH_HUD_ALWAYS_DEAD" = HEALTH_HUD_ALWAYS_DEAD,
	"PARALYSE_RESISTANT" = PARALYSE_RESISTANT,
	"ROBOTIC_LIMBS" = ROBOTIC_LIMBS,
	"GREYSCALE_BLOOD" = GREYSCALE_BLOOD,
	"IS_INSULATED" = IS_INSULATED
))

DEFINE_BITFIELD(damagetype, list(
	"BRUTELOSS" = BRUTELOSS,
	"FIRELOSS" = FIRELOSS,
	"TOXLOSS" = TOXLOSS,
	"OXYLOSS" = OXYLOSS,
	"STAMINALOSS" = STAMINALOSS
))

DEFINE_BITFIELD(disabilities, list(
	"BLIND" = BLIND,
	"DEAF" = DEAF,
	"NEARSIGHTED" = NEARSIGHTED
))

DEFINE_BITFIELD(protection, list(
	"CONFIG_ENTRY_LOCKED" = CONFIG_ENTRY_LOCKED,
	"CONFIG_ENTRY_HIDDEN" = CONFIG_ENTRY_HIDDEN
))

DEFINE_BITFIELD(ammo_behavior_flags, list(
	"AMMO_TARGET_TURF" = AMMO_TARGET_TURF,
	"AMMO_XENO" = AMMO_XENO,
	"AMMO_UNWIELDY" = AMMO_UNWIELDY,
	"AMMO_ENERGY" = AMMO_ENERGY,
	"AMMO_BETTER_COVER_RNG" = AMMO_BETTER_COVER_RNG,
	"AMMO_INCENDIARY" = AMMO_INCENDIARY,
	"AMMO_SKIPS_ALIENS" = AMMO_SKIPS_ALIENS,
	"AMMO_BALLISTIC" = AMMO_BALLISTIC,
	"AMMO_SPECIAL_PROCESS" = AMMO_SPECIAL_PROCESS,
	"AMMO_FLAME" = AMMO_FLAME,
	"AMMO_IFF" = AMMO_IFF,
	"AMMO_HITSCAN" = AMMO_HITSCAN,
	"AMMO_LEAVE_TURF" = AMMO_LEAVE_TURF,
	"AMMO_PASS_THROUGH_TURF" = AMMO_PASS_THROUGH_TURF,
	"AMMO_PASS_THROUGH_MOVABLE" = AMMO_PASS_THROUGH_MOVABLE,
	"AMMO_PASS_THROUGH_MOB" = AMMO_PASS_THROUGH_MOB,
	"AMMO_SOUND_PITCH" = AMMO_SOUND_PITCH,
	"AMMO_SNIPER" = AMMO_SNIPER
))

DEFINE_BITFIELD(attach_features_flags, list(
	"ATTACH_REMOVABLE" = ATTACH_REMOVABLE,
	"ATTACH_ACTIVATION" = ATTACH_ACTIVATION,
	"ATTACH_SAME_ICON" = ATTACH_SAME_ICON,
	"ATTACH_APPLY_ON_MOB" = ATTACH_APPLY_ON_MOB,
	"ATTACH_SEPERATE_MOB_OVERLAY" = ATTACH_SEPERATE_MOB_OVERLAY,
	"ATTACH_NO_HANDS" = ATTACH_NO_HANDS,
	"ATTACH_BYPASS_ALLOWED_LIST" = ATTACH_BYPASS_ALLOWED_LIST,
	"ATTACH_DIFFERENT_MOB_ICON_STATE" = ATTACH_DIFFERENT_MOB_ICON_STATE
))

DEFINE_BITFIELD(barrier_flags, list(
	"HANDLE_BARRIER_CHANCE" = HANDLE_BARRIER_CHANCE,
	"HANDLE_BARRIER_BLOCK" = HANDLE_BARRIER_BLOCK
))

DEFINE_BITFIELD(item_flags, list(
	"IN_INVENTORY" = IN_INVENTORY,
	"NOBLUDGEON" = NOBLUDGEON,
	"DELONDROP" = DELONDROP,
	"TWOHANDED" = TWOHANDED,
	"WIELDED" = WIELDED,
	"ITEM_ABSTRACT" = ITEM_ABSTRACT,
	"DOES_NOT_NEED_HANDS" = DOES_NOT_NEED_HANDS,
	"SYNTH_RESTRICTED" = SYNTH_RESTRICTED,
	"IMPEDE_JETPACK" = IMPEDE_JETPACK,
	"CAN_BUMP_ATTACK" = CAN_BUMP_ATTACK,
	"IS_DEPLOYABLE" = IS_DEPLOYABLE,
	"DEPLOY_ON_INITIALIZE" = DEPLOY_ON_INITIALIZE,
	"IS_DEPLOYED" = IS_DEPLOYED,
	"DEPLOYED_NO_PICKUP" = DEPLOYED_NO_PICKUP,
	"DEPLOYED_NO_ROTATE" = DEPLOYED_NO_ROTATE,
	"DEPLOYED_NO_ROTATE_ANCHORED" = DEPLOYED_NO_ROTATE_ANCHORED,
	"DEPLOYED_WRENCH_DISASSEMBLE" = DEPLOYED_WRENCH_DISASSEMBLE,
	"DEPLOYED_ANCHORED_FIRING_ONLY" = DEPLOYED_ANCHORED_FIRING_ONLY,
	"FULLY_WIELDED" = FULLY_WIELDED,
	"HAS_UNDERLAY" = HAS_UNDERLAY,
	"AUTOBALANCE_CHECK" = AUTOBALANCE_CHECK,
	"IN_STORAGE" = IN_STORAGE,
	"CAN_REFILL" = CAN_REFILL
))

DEFINE_BITFIELD(storage_flags, list(
	"BYPASS_VENDOR_CHECK" = BYPASS_VENDOR_CHECK
))

DEFINE_BITFIELD(id_flags, list(
	"CAN_BUY_LOADOUT" = CAN_BUY_LOADOUT,
	"USED_GHMME" = USED_GHMME
))

DEFINE_BITFIELD(ghost_hud, list(
	"GHOST_HUD_MED" = GHOST_HUD_MED,
	"GHOST_HUD_SEC" = GHOST_HUD_SEC,
	"GHOST_HUD_SQUAD" = GHOST_HUD_SQUAD,
	"GHOST_HUD_XENO" = GHOST_HUD_XENO,
	"GHOST_HUD_ORDER" = GHOST_HUD_ORDER
))

DEFINE_BITFIELD(toggles_sound, list(
	"SOUND_ADMINHELP" = SOUND_ADMINHELP,
	"SOUND_MIDI" = SOUND_MIDI,
	"SOUND_AMBIENCE" = SOUND_AMBIENCE,
	"SOUND_LOBBY" = SOUND_LOBBY,
	"SOUND_INSTRUMENTS_OFF" = SOUND_INSTRUMENTS_OFF,
	"SOUND_WEATHER" = SOUND_WEATHER,
	"SOUND_NOENDOFROUND" = SOUND_NOENDOFROUND
))

DEFINE_BITFIELD(toggles_gameplay, list(
	"RADIAL_MEDICAL" = RADIAL_MEDICAL,
	"MIDDLESHIFTCLICKING" = MIDDLESHIFTCLICKING,
	"RADIAL_STACKS" = RADIAL_STACKS,
	"AUTO_INTERACT_DEPLOYABLES" = AUTO_INTERACT_DEPLOYABLES,
	"RADIAL_LASERGUNS" = RADIAL_LASERGUNS,
	"DIRECTIONAL_ATTACKS" = DIRECTIONAL_ATTACKS,
	"TOGGLE_CLICKDRAG" = TOGGLE_CLICKDRAG,
	"TOGGLE_XENO_MOVE_INTENT_KEYBIND" = TOGGLE_XENO_MOVE_INTENT_KEYBIND
))

DEFINE_BITFIELD(toggles_deadchat, list(
	"DISABLE_DEATHRATTLE" = DISABLE_DEATHRATTLE,
	"DISABLE_ARRIVALRATTLE" = DISABLE_ARRIVALRATTLE
))

DEFINE_BITFIELD(toggles_chat, list(
	"CHAT_OOC" = CHAT_OOC,
	"CHAT_DEAD" = CHAT_DEAD,
	"CHAT_GHOSTEARS" = CHAT_GHOSTEARS,
	"CHAT_GHOSTSIGHT" = CHAT_GHOSTSIGHT,
	"CHAT_PRAYER" = CHAT_PRAYER,
	"CHAT_RADIO" = CHAT_RADIO,
	"CHAT_ATTACKLOGS" = CHAT_ATTACKLOGS,
	"CHAT_DEBUGLOGS" = CHAT_DEBUGLOGS,
	"CHAT_GHOSTRADIO" = CHAT_GHOSTRADIO,
	"CHAT_FFATTACKLOGS" = CHAT_FFATTACKLOGS,
	"CHAT_ENDROUNDLOGS" = CHAT_ENDROUNDLOGS,
	"CHAT_GHOSTHIVEMIND" = CHAT_GHOSTHIVEMIND,
	"CHAT_STATISTICS" = CHAT_STATISTICS,
	"CHAT_LOOC" = CHAT_LOOC
))

DEFINE_BITFIELD(scuttle_flags, list(
	"FLAGS_EVACUATION_DENY" = FLAGS_EVACUATION_DENY,
	"FLAGS_SELF_DESTRUCT_DENY" = FLAGS_SELF_DESTRUCT_DENY,
	"FLAGS_SDEVAC_TIMELOCK" = FLAGS_SDEVAC_TIMELOCK
))

DEFINE_BITFIELD(buckle_flags, list(
	"CAN_BUCKLE" = CAN_BUCKLE,
	"CAN_BE_BUCKLED" = CAN_BE_BUCKLED,
	"BUCKLE_REQUIRES_RESTRAINTS" = BUCKLE_REQUIRES_RESTRAINTS,
	"BUCKLE_PREVENTS_PULL" = BUCKLE_PREVENTS_PULL,
	"BUCKLE_NEEDS_HAND" = BUCKLE_NEEDS_HAND,
	"BUCKLE_NEEDS_TWO_HANDS" = BUCKLE_NEEDS_TWO_HANDS
))

DEFINE_BITFIELD(resistance_flags, list(
	"INDESTRUCTIBLE" = INDESTRUCTIBLE,
	"UNACIDABLE" = UNACIDABLE,
	"ON_FIRE" = ON_FIRE,
	"XENO_DAMAGEABLE" = XENO_DAMAGEABLE,
	"DROPSHIP_IMMUNE" = DROPSHIP_IMMUNE,
	"CRUSHER_IMMUNE" = CRUSHER_IMMUNE,
	"PLASMACUTTER_IMMUNE" = PLASMACUTTER_IMMUNE,
	"PROJECTILE_IMMUNE" = PROJECTILE_IMMUNE,
	"PORTAL_IMMUNE" = PORTAL_IMMUNE
))

DEFINE_BITFIELD(restrained_flags, list(
	"RESTRAINED_XENO_NEST" = RESTRAINED_XENO_NEST,
	"RESTRAINED_NECKGRAB" = RESTRAINED_NECKGRAB,
	"RESTRAINED_STRAIGHTJACKET" = RESTRAINED_STRAIGHTJACKET,
	"RESTRAINED_RAZORWIRE" = RESTRAINED_RAZORWIRE,
	"RESTRAINED_PSYCHICGRAB" = RESTRAINED_PSYCHICGRAB
))

DEFINE_BITFIELD(vision_flags, list(
	"SEE_INFRA" = SEE_INFRA,
	"SEE_SELF" = SEE_SELF,
	"SEE_MOBS" = SEE_MOBS,
	"SEE_OBJS" = SEE_OBJS,
	"SEE_TURFS" = SEE_TURFS,
	"SEE_PIXELS" = SEE_PIXELS,
	"SEE_THRU" = SEE_THRU,
	"SEE_BLACKNESS" = SEE_BLACKNESS,
	"BLIND" = BLIND
))

DEFINE_BITFIELD(sight, list(
	"SEE_INFRA" = SEE_INFRA,
	"SEE_SELF" = SEE_SELF,
	"SEE_MOBS" = SEE_MOBS,
	"SEE_OBJS" = SEE_OBJS,
	"SEE_TURFS" = SEE_TURFS,
	"SEE_PIXELS" = SEE_PIXELS,
	"SEE_THRU" = SEE_THRU,
	"SEE_BLACKNESS" = SEE_BLACKNESS,
	"BLIND" = BLIND
))

DEFINE_BITFIELD(use_state_flags, list(
	"ABILITY_USE_INCAP" = ABILITY_USE_INCAP,
	"ABILITY_USE_LYING" = ABILITY_USE_LYING,
	"ABILITY_USE_BUCKLED" = ABILITY_USE_BUCKLED,
	"ABILITY_USE_STAGGERED" = ABILITY_USE_STAGGERED,
	"ABILITY_USE_FORTIFIED" = ABILITY_USE_FORTIFIED,
	"ABILITY_USE_CRESTED" = ABILITY_USE_CRESTED,
	"ABILITY_USE_NOTTURF" = ABILITY_USE_NOTTURF,
	"ABILITY_USE_BUSY" = ABILITY_USE_BUSY,
	"ABILITY_TARGET_SELF" = ABILITY_TARGET_SELF,
	"ABILITY_IGNORE_PLASMA" = ABILITY_IGNORE_PLASMA,
	"ABILITY_USE_SOLIDOBJECT" = ABILITY_USE_SOLIDOBJECT,
	"ABILITY_IGNORE_COOLDOWN" = ABILITY_IGNORE_COOLDOWN,
	"ABILITY_IGNORE_DEAD_TARGET" = ABILITY_IGNORE_DEAD_TARGET,
	"ABILITY_IGNORE_SELECTED_ABILITY" = ABILITY_IGNORE_SELECTED_ABILITY,
	"ABILITY_DO_AFTER_ATTACK" = ABILITY_DO_AFTER_ATTACK,
	"ABILITY_USE_BURROWED" = ABILITY_USE_BURROWED
))

DEFINE_BITFIELD(pipe_flags, list(
	"PIPING_ALL_LAYER" = PIPING_ALL_LAYER,
	"PIPING_ONE_PER_TURF" = PIPING_ONE_PER_TURF,
	"PIPING_DEFAULT_LAYER_ONLY" = PIPING_DEFAULT_LAYER_ONLY,
	"PIPING_CARDINAL_AUTONORMALIZE" = PIPING_CARDINAL_AUTONORMALIZE
))

DEFINE_BITFIELD(turret_flags, list(
	"TURRET_SAFETY" = TURRET_SAFETY,
	"TURRET_LOCKED" = TURRET_LOCKED,
	"TURRET_ON" = TURRET_ON,
	"TURRET_HAS_CAMERA" = TURRET_HAS_CAMERA,
	"TURRET_ALERTS" = TURRET_ALERTS,
	"TURRET_RADIAL" = TURRET_RADIAL,
	"TURRET_IMMOBILE" = TURRET_IMMOBILE,
	"TURRET_INACCURATE" = TURRET_INACCURATE
))

DEFINE_BITFIELD(interaction_flags, list(
	"INTERACT_REQUIRES_DEXTERITY" = INTERACT_REQUIRES_DEXTERITY,
	"INTERACT_CHECK_INCAPACITATED" = INTERACT_CHECK_INCAPACITATED,
	"INTERACT_UI_INTERACT" = INTERACT_UI_INTERACT,
	"INTERACT_SILICON_ALLOWED" = INTERACT_SILICON_ALLOWED,
	"INTERACT_POWERLOADER_PICKUP_ALLOWED" = INTERACT_POWERLOADER_PICKUP_ALLOWED,
	"INTERACT_POWERLOADER_PICKUP_ALLOWED_BYPASS_ANCHOR" = INTERACT_POWERLOADER_PICKUP_ALLOWED_BYPASS_ANCHOR
))

DEFINE_BITFIELD(job_flags, list(
	"JOB_FLAG_SPECIALNAME" = JOB_FLAG_SPECIALNAME,
	"JOB_FLAG_LATEJOINABLE" = JOB_FLAG_LATEJOINABLE,
	"JOB_FLAG_ROUNDSTARTJOINABLE" = JOB_FLAG_ROUNDSTARTJOINABLE,
	"JOB_FLAG_NOHEADSET" = JOB_FLAG_NOHEADSET,
	"JOB_FLAG_ALLOWS_PREFS_GEAR" = JOB_FLAG_ALLOWS_PREFS_GEAR,
	"JOB_FLAG_PROVIDES_BANK_ACCOUNT" = JOB_FLAG_PROVIDES_BANK_ACCOUNT,
	"JOB_FLAG_OVERRIDELATEJOINSPAWN" = JOB_FLAG_OVERRIDELATEJOINSPAWN,
	"JOB_FLAG_ADDTOMANIFEST" = JOB_FLAG_ADDTOMANIFEST,
	"JOB_FLAG_ISCOMMAND" = JOB_FLAG_ISCOMMAND,
	"JOB_FLAG_BOLD_NAME_ON_SELECTION" = JOB_FLAG_BOLD_NAME_ON_SELECTION,
	"JOB_FLAG_PROVIDES_SQUAD_HUD" = JOB_FLAG_PROVIDES_SQUAD_HUD,
	"JOB_FLAG_HIDE_CURRENT_POSITIONS" = JOB_FLAG_HIDE_CURRENT_POSITIONS,
	"JOB_FLAG_CAN_SEE_ORDERS" = JOB_FLAG_CAN_SEE_ORDERS,
	"JOB_FLAG_ALWAYS_VISIBLE_ON_MINIMAP" = JOB_FLAG_ALWAYS_VISIBLE_ON_MINIMAP,
	"JOB_FLAG_SHOW_OPEN_POSITIONS" = JOB_FLAG_SHOW_OPEN_POSITIONS,
	"JOB_FLAG_LOUDER_TTS" = JOB_FLAG_LOUDER_TTS
))

DEFINE_BITFIELD(lock_flags, list(
	"SQUAD_LOCK" = SQUAD_LOCK,
	"JOB_LOCK" = JOB_LOCK
))

DEFINE_BITFIELD(smoothing_flags, list(
	"SMOOTH_CORNERS" = SMOOTH_CORNERS,
	"SMOOTH_BITMASK" = SMOOTH_BITMASK,
	"SMOOTH_DIAGONAL_CORNERS" = SMOOTH_DIAGONAL_CORNERS,
	"SMOOTH_BORDER" = SMOOTH_BORDER,
	"SMOOTH_QUEUED" = SMOOTH_QUEUED,
	"SMOOTH_OBJ" = SMOOTH_OBJ
))

DEFINE_BITFIELD(dropship_equipment_flags, list(
	"IS_NOT_REMOVABLE" = IS_NOT_REMOVABLE,
	"USES_AMMO" = USES_AMMO,
	"IS_WEAPON" = IS_WEAPON,
	"FIRE_MISSION_ONLY" = FIRE_MISSION_ONLY,
	"IS_INTERACTABLE" = IS_INTERACTABLE
))

DEFINE_BITFIELD(smoothing_junction, list(
	"NORTH_JUNCTION" = NORTH_JUNCTION,
	"SOUTH_JUNCTION" = SOUTH_JUNCTION,
	"EAST_JUNCTION" = EAST_JUNCTION,
	"WEST_JUNCTION" = WEST_JUNCTION,
	"NORTHEAST_JUNCTION" = NORTHEAST_JUNCTION,
	"SOUTHEAST_JUNCTION" = SOUTHEAST_JUNCTION,
	"SOUTHWEST_JUNCTION" = SOUTHWEST_JUNCTION,
	"NORTHWEST_JUNCTION" = NORTHWEST_JUNCTION
))

DEFINE_BITFIELD(xeno_flags, list(
	"XENO_LEAPING" = XENO_LEAPING,
	"XENO_LEADER" = XENO_LEADER,
	"XENO_ZOOMED" = XENO_ZOOMED,
	"XENO_MOBHUD" = XENO_MOBHUD,
	"XENO_ROUNY" = XENO_ROUNY
))

DEFINE_BITFIELD(sec_level_flags, list(
	"SEC_LEVEL_FLAG_CAN_SWITCH_COMMS_CONSOLE" = SEC_LEVEL_FLAG_CAN_SWITCH_COMMS_CONSOLE,
	"SEC_LEVEL_FLAG_CAN_SWITCH_WITH_AUTH" = SEC_LEVEL_FLAG_CAN_SWITCH_WITH_AUTH,
	"SEC_LEVEL_FLAG_CANNOT_SWITCH" = SEC_LEVEL_FLAG_CANNOT_SWITCH,
	"SEC_LEVEL_FLAG_RED_LIGHTS" = SEC_LEVEL_FLAG_RED_LIGHTS,
	"SEC_LEVEL_FLAG_STATE_OF_EMERGENCY" = SEC_LEVEL_FLAG_STATE_OF_EMERGENCY
))

DEFINE_BITFIELD(vis_flags, list(
	"VIS_HIDE" = VIS_HIDE,
	"VIS_INHERIT_DIR" = VIS_INHERIT_DIR,
	"VIS_INHERIT_ICON" = VIS_INHERIT_ICON,
	"VIS_INHERIT_ICON_STATE" = VIS_INHERIT_ICON_STATE,
	"VIS_INHERIT_ID" = VIS_INHERIT_ID,
	"VIS_INHERIT_LAYER" = VIS_INHERIT_LAYER,
	"VIS_INHERIT_PLANE" = VIS_INHERIT_PLANE,
	"VIS_UNDERLAY" = VIS_UNDERLAY,
))

DEFINE_BITFIELD(round_type_flags, list(
	"MODE_INFESTATION" = MODE_INFESTATION,
	"MODE_NO_LATEJOIN" = MODE_NO_LATEJOIN,
	"MODE_LATE_OPENING_SHUTTER_TIMER" = MODE_LATE_OPENING_SHUTTER_TIMER,
	"MODE_XENO_SPAWN_PROTECT" = MODE_XENO_SPAWN_PROTECT,
	"MODE_PSY_POINTS" = MODE_PSY_POINTS,
	"MODE_PSY_POINTS_ADVANCED" = MODE_PSY_POINTS_ADVANCED,
	"MODE_HIJACK_POSSIBLE" = MODE_HIJACK_POSSIBLE,
	"MODE_XENO_GRAB_DEAD_ALLOWED" = MODE_XENO_GRAB_DEAD_ALLOWED,
	"MODE_SILO_RESPAWN" = MODE_SILO_RESPAWN,
	"MODE_HUMAN_ONLY" = MODE_HUMAN_ONLY,
	"MODE_TWO_HUMAN_FACTIONS" = MODE_TWO_HUMAN_FACTIONS,
	"MODE_NO_PERMANENT_WOUNDS" = MODE_NO_PERMANENT_WOUNDS,
	"MODE_SILOS_SPAWN_MINIONS" = MODE_SILOS_SPAWN_MINIONS,
	"MODE_ALLOW_XENO_QUICKBUILD" = MODE_ALLOW_XENO_QUICKBUILD,
	"MODE_DISALLOW_RAILGUN" = MODE_DISALLOW_RAILGUN,
	"MODE_FORCE_CUSTOMSQUAD_UI" = MODE_FORCE_CUSTOMSQUAD_UI,
	"MODE_MUTATIONS_OBTAINABLE" = MODE_MUTATIONS_OBTAINABLE
))
