GLOBAL_VAR(log_directory)
GLOBAL_PROTECT(log_directory)
GLOBAL_VAR(world_game_log)
GLOBAL_PROTECT(world_game_log)
GLOBAL_VAR(world_runtime_log)
GLOBAL_PROTECT(world_runtime_log)
GLOBAL_VAR(world_qdel_log)
GLOBAL_PROTECT(world_qdel_log)
GLOBAL_VAR(world_attack_log)
GLOBAL_PROTECT(world_attack_log)
GLOBAL_VAR(world_href_log)
GLOBAL_PROTECT(world_href_log)
GLOBAL_VAR(round_id)
GLOBAL_PROTECT(round_id)
GLOBAL_VAR(config_error_log)
GLOBAL_PROTECT(config_error_log)
GLOBAL_VAR(sql_error_log)
GLOBAL_PROTECT(sql_error_log)
GLOBAL_VAR(world_telecomms_log)
GLOBAL_PROTECT(world_telecomms_log)
GLOBAL_VAR(world_manifest_log)
GLOBAL_PROTECT(world_manifest_log)
GLOBAL_VAR(world_paper_log)
GLOBAL_PROTECT(world_paper_log)


GLOBAL_LIST_EMPTY(admin_log)
GLOBAL_PROTECT(admin_log)
GLOBAL_LIST_EMPTY(adminprivate_log)
GLOBAL_PROTECT(adminprivate_log)
GLOBAL_LIST_EMPTY(game_log)
GLOBAL_PROTECT(game_log)
GLOBAL_LIST_EMPTY(access_log)
GLOBAL_PROTECT(access_log)

GLOBAL_LIST_EMPTY(asay_log)
GLOBAL_PROTECT(asay_log)
GLOBAL_LIST_EMPTY(msay_log)
GLOBAL_PROTECT(msay_log)
GLOBAL_LIST_EMPTY(dsay_log)
GLOBAL_PROTECT(dsay_log)

GLOBAL_LIST_EMPTY(ffattack_log)
GLOBAL_PROTECT(ffattack_log)

GLOBAL_LIST_EMPTY(explosion_log)
GLOBAL_PROTECT(explosion_log)