/obj/vehicle/sealed/armored/multitile/apc
	name = "\improper APC - Athena"
	desc = "An unarmed command APC designed to command and transport troops in the battlefield."
	icon = 'icons/obj/armored/3x3/apc.dmi'
	icon_state = "apc"
	damage_icon_path = 'icons/obj/armored/3x3/apc_damage_overlay.dmi'
	armored_flags = ARMORED_HAS_HEADLIGHTS
	required_entry_skill = SKILL_LARGE_VEHICLE_DEFAULT
	minimap_icon_state = null
	turret_icon = null
	interior = null
	secondary_turret_icon = null
	primary_weapon_type = null
	secondary_weapon_type = null
	armored_flags = NONE
	pixel_x = -48
	pixel_y = -40
	obj_integrity = 2000
	max_integrity = 2000
	max_occupants = 10 //Clown car? Clown car.
	move_delay = 0.5 SECONDS
