GLOBAL_LIST_EMPTY(ai_names)                  
GLOBAL_LIST_EMPTY(wizard_first)              
GLOBAL_LIST_EMPTY(wizard_second)             
GLOBAL_LIST_EMPTY(ninja_titles)              
GLOBAL_LIST_EMPTY(ninja_names)               
GLOBAL_LIST_EMPTY(commando_names)            
GLOBAL_LIST_EMPTY(first_names_male)          
GLOBAL_LIST_EMPTY(first_names_female)        
GLOBAL_LIST_EMPTY(first_names_male_russian)  
GLOBAL_LIST_EMPTY(first_names_female_russian)
GLOBAL_LIST_EMPTY(first_names_male_pmc)      
GLOBAL_LIST_EMPTY(first_names_female_pmc)    
GLOBAL_LIST_EMPTY(first_names_male_clf)      
GLOBAL_LIST_EMPTY(first_names_female_clf)    
GLOBAL_LIST_EMPTY(last_names)                
GLOBAL_LIST_EMPTY(last_names_russian)        
GLOBAL_LIST_EMPTY(last_names_pmc)            
GLOBAL_LIST_EMPTY(last_names_clf)            
GLOBAL_LIST_EMPTY(clown_names)               
GLOBAL_LIST_EMPTY(moth_first)                
GLOBAL_LIST_EMPTY(moth_last)                 
GLOBAL_LIST_EMPTY(verbs)                     
GLOBAL_LIST_EMPTY(adjectives)                
GLOBAL_LIST_EMPTY(food_adjectives)           

// because why have a 2nd file, this is literally the best place for it.

GLOB.ai_names = file2list("strings/names/ai.txt")
GLOB.wizard_first = file2list("strings/names/wizardfirst.txt")
GLOB.wizard_second = file2list("strings/names/wizardsecond.txt")
GLOB.ninja_titles = file2list("strings/names/ninjatitle.txt")
GLOB.ninja_names = file2list("strings/names/ninjaname.txt")
GLOB.commando_names = file2list("strings/names/death_commando.txt")
GLOB.first_names_male = file2list("strings/names/first_male.txt")
GLOB.first_names_female = file2list("strings/names/first_female.txt")
GLOB.first_names_male_russian = file2list("strings/names/first_male_russian.txt")
GLOB.first_names_female_russian = file2list("strings/names/first_female_russian.txt")
GLOB.first_names_male_pmc = file2list("strings/names/first_male_pmc.txt")
GLOB.first_names_female_pmc = file2list("strings/names/first_female_pmc.txt")
GLOB.first_names_male_clf = file2list("strings/names/first_male_clf.txt")
GLOB.first_names_female_clf = file2list("strings/names/first_female_clf.txt")
GLOB.last_names = file2list("strings/names/last_name.txt")
GLOB.last_names_russian = file2list("strings/names/last_name_russian.txt")
GLOB.last_names_pmc = file2list("strings/names/last_name_pmc.txt")
GLOB.last_names_clf = file2list("strings/names/last_name_clf.txt")
GLOB.clown_names = file2list("strings/names/clown.txt")
GLOB.moth_first = file2list("strings/names/moth_first.txt")
GLOB.moth_last = file2list("strings/names/moth_last.txt")
GLOB.verbs = file2list("strings/names/verbs.txt")
GLOB.adjectives = file2list("strings/names/adjectives.txt")
GLOB.food_adjectives = file2list("strings/names/food_adjectives.txt")