#include "code\modules\factory\unboxer.dm"
#include "code\modules\factory\parts.dm"
#include "code\modules\factory\howtopaper.dm"
#include "code\datums\jobs\job\mothellian.dm"
#include "code\modules\clothing\head\head.dm"
#include "code\modules\clothing\suits\marine_armor.dm"
#include "code\modules\clothing\under\marine_uniform.dm"
