//Flags for the get_nearest_target
#define TARGET_HUMAN_TURRETS (1<<0)
#define TARGET_XENO_TURRETS (1<<1)
#define TARGET_HUMAN (1<<2)
#define TARGET_XENO (1<<3)

#define TARGET_ALL (TARGET_HUMAN_TURRETS|TARGET_XENO_TURRETS|TARGET_HUMAN|TARGET_XENO)
