#define COLOR_INPUT_DISABLED	"#F0F0F0"
#define COLOR_INPUT_ENABLED		"#D3B5B5"

#define COLOR_WHITE            "#EEEEEE"
#define COLOR_GRAY             "#808080"
#define COLOR_BLACK            "#000000"
#define COLOR_RED              "#FF0000"
#define COLOR_YELLOW           "#FFFF00"
#define COLOR_GREEN            "#008000"
#define COLOR_CYAN             "#00FFFF"
#define COLOR_BLUE             "#0000FF"
#define COLOR_PINK             "#FFC0CB"
#define COLOR_MAGENTA          "#FF00FF"
#define COLOR_PURPLE           "#800080"
#define COLOR_ORANGE           "#FF9900"
#define COLOR_BROWN            "#BA9F6D"
