#define FACTORY_MACHINE_CUTTER	1
#define FACTORY_MACHINE_HEATER	2
#define FACTORY_MACHINE_FORMER	3
#define FACTORY_MACHINE_FLATTER	4

#define STEP_NEXT_MACHINE STEP_NEXT_MACHINE
#define STEP_ICON_STATE "iconstate"
