#define FACTORY_MACHINE_CUTTER	1
#define FACTORY_MACHINE_HEATER	2
#define FACTORY_MACHINE_FORMER	3
#define FACTORY_MACHINE_FLATTER	4
#define FACTORY_MACHINE_CONSTRUCTOR 5
#define FACTORY_MACHINE_DRILLER 6
#define FACTORY_MACHINE_GALVANIZER 7
#define FACTORY_MACHINE_COMPRESSOR 8

#define STEP_NEXT_MACHINE "next_machine"
#define STEP_ICON_STATE "iconstate"
