#define GAMEMODE_SURIVOR_DRAW "Draw"
#define GAMEMODE_SURIVOR_HUMAN_WIN "Survivors Win"
#define GAMEMODE_SURIVOR_XENO_WIN "Xeno Win"

#define SURVIVOR_BUILDER "SURVIVOR_BUILDER"
#define SURVIVOR_MEDIC "SURVIVOR_MEDIC"
#define SURVIVOR_FIGHTER "SURVIVOR_FIGHTER"
#define SURVIVOR_SCAV "SURVIVOR_SCAV"