//Generic /obj/item/implant flags
#define GRANT_ACTIVATION_ACTION (1<<0)
#define ACTIVATE_ON_HEAR (1<<1)

#define MALFUNCTION_NONE 0
#define MALFUNCTION_TEMPORARY 1
#define MALFUNCTION_PERMANENT 2

#define MAX_IMPLANT_REAGENTS 200
