
#define MINIMAP_FLAG_XENO (1<<0)
#define MINIMAP_FLAG_MARINE (1<<1)
#define MINIMAP_FLAG_MARINE_REBEL (1<<2)
#define MINIMAP_FLAG_ALL (1<<3) - 1

#define MINIMAP_FLAG_EXCAVATION_ZONE (1<<3)


#define MINIMAP_FILE_DIR "maps/minimaps/"
