#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_MULTIPLICATIVE_SLOWDOWN 3
#define MOVESPEED_DATA_INDEX_CONFLICT 4

#define MOVESPEED_DATA_INDEX_MAX 4

//ids

#define MOVESPEED_ID_MOB_WALK_RUN_CONFIG_SPEED "MOB_WALK_RUN"
#define MOVESPEED_ID_MOB_GRAB_STATE "MOB_GRAB_STATE"
#define MOVESPEED_ID_CONFIG_SPEEDMOD "MOB_CONFIG_MODIFIER"

#define MOVESPEED_ID_ADMIN_VAREDIT "ADMIN_VAREDIT_MODIFIER"

#define MOVESPEED_ID_DAMAGE_SLOWDOWN "DAMAGE"
#define MOVESPEED_ID_STAGGERSTUN "STAGGERSTUN"
#define MOVESPEED_ID_DROWSINESS "DROWSINESS"

#define MOVESPEED_ID_XENO_CASTE_SPEED "XENO_CASTE_SPEED"
#define MOVESPEED_ID_XENO_CHARGE "XENO_CHARGE_MODIFIER"
#define MOVESPEED_ID_ENHANCEMENT "ENHANCEMENT"
#define MOVESPEED_ID_CRESTDEFENSE "CRESTDEFENSE"
#define MOVESPEED_ID_WARRIOR_AGILITY "WARRIOR_AGILITY"
#define MOVESPEED_ID_FRENZY_AURA "FRENZY_AURA"
#define MOVESPEED_ID_XENO_HEMODILE "XENO_HEMODILE"
#define MOVESPEED_ID_RAVAGER_RAGE "RAVAGER_RAGE"
#define MOVESPEED_ID_GORGER_CARNAGE "GORGER_CARNAGE"
#define MOVESPEED_ID_GORGER_REJUVENATE "GORGER_REJUVENATE"
#define MOVESPEED_ID_SNATCH "RUNNER_SNATCH"
#define MOVESPEED_ID_BLESSED_HIVE "BLESSED_HIVE" //#blessed.
#define MOVESPEED_ID_WARLOCK_CHANNELING "WARLOCK_CHANNELING"
#define MOVESPEED_ID_XENO_DREAD "DREADXENO"
#define MOVESPEED_ID_BEHEMOTH_PRIMAL_WRATH "BEHEMOTH_PRIMAL_WRATH"

#define MOVESPEED_ID_SIMPLEMOB_VARSPEED "SIMPLEMOB_VARSPEED_MODIFIER"

#define MOVESPEED_ID_SPECIES "SPECIES_SPEED_MOD"

#define MOVESPEED_ID_BULKY_DRAGGING "BULKY_DRAG"
#define MOVESPEED_ID_HUMAN_CARRYING "HUMAN_CARRY"
#define MOVESPEED_ID_COLD "COLD"
#define MOVESPEED_ID_HUNGRY "HUNGRY"
#define MOVESPEED_ID_PAIN "PAIN"

#define MOVESPEED_ID_MOBILITY_AURA "MOBLITY_AURA"

#define MOVESPEED_ID_AIM_SLOWDOWN "AIM_SLOWDOWN"
#define MOVESPEED_ID_AIM_MODE_SLOWDOWN "AIM_MODE_SLOWDOWN"
#define MOVESPEED_ID_SCOPE_SLOWDOWN "SCOPE_SLOWDOWN"
#define MOVESPEED_ID_HARVEST_TRAM_SLOWDOWN "HARVEST_TRAM_SLOWDOWN"
#define MOVESPEED_ID_CHEM_CONNECT "CHEM_CONNECT"
#define MOVESPEED_ID_VALI_BOOST "VALI_BOOST"

#define MOVESPEED_ID_MINDMELD "MINDMELD"

//Specific slowdown bitfield
#define SLOWDOWN_IMPEDE_JETPACK (1<<0) //Reduce the range of jetpack
