#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_MULTIPLICATIVE_SLOWDOWN 3
#define MOVESPEED_DATA_INDEX_CONFLICT 4

#define MOVESPEED_DATA_INDEX_MAX 4

//ids

#define MOVESPEED_ID_ADMIN_VAREDIT						"ADMIN_VAREDIT_MODIFIER"

#define MOVESPEED_ID_XENO_CHARGE						"XENO_CHARGE_MODIFIER"
