#define SPECIES_LIMB_GENERIC 0
#define SPECIES_LIMB_HUMAN 1
#define SPECIES_LIMB_CLONE 2


#define STIM_DURATION_DEFAULT 10 MINUTES
#define MAX_ACTIVE_STIMS 5
#define MAX_STIM_SEQUENCES 10

#define STIM_ALLOW_DUPE (1<<0)
#define STIM_ABSTRACT (1<<1)
