// Used to direct channels to speak into.
#define SAY_CHANNEL "Say"
#define RADIO_CHANNEL "Radio"
#define ME_CHANNEL "Me"
#define OOC_CHANNEL "OOC"
#define LOOC_CHANNEL "LOOC"
#define MOOC_CHANNEL "MOOC"
#define XOOC_CHANNEL "XOOC"
#define XMOOC_CHANNEL "XMOOC"
#define WHISPER_CHANNEL "Whisper"
#define SUBTLE_CHANNEL "Subtle"
#define SUBTLER_CHANNEL "Subtler"
#define ADMIN_CHANNEL "Admin"
#define MENTOR_CHANNEL "Mentor"
