// Used to direct channels to speak into.
#define SAY_CHANNEL "Say"
#define RADIO_CHANNEL "Radio"
#define ME_CHANNEL "Me"
#define OOC_CHANNEL "OOC"
#define LOOC_CHANNEL "LOOC"
#define MOOC_CHANNEL "MOOC"
#define XOOC_CHANNEL "XOOC"
#define ADMIN_CHANNEL "Admin"
#define MENTOR_CHANNEL "Mentor"
