#define VEHICLE_MUST_TURN (1<<0)

#define TURRET_TYPE_DROIDLASER 3
#define TURRET_TYPE_HEAVY 2
#define TURRET_TYPE_LIGHT 1
#define TURRET_TYPE_EXPLOSIVE 0

#define PATTERN_TRACKED 1
#define PATTERN_DROID 2
