
//meson goggles

/obj/item/clothing/glasses/meson
	name = "optical meson scanner"
	desc = "Used to shield the user's eyes from harmful electromagnetic emissions, also used as general safety goggles. Not adequate as welding protection."
	icon_state = "meson"
	item_state = "glasses"
	actions_types = list(/datum/action/item_action/toggle)
	origin_tech = "magnets=2;engineering=2"
	toggleable = 1
	fullscreen_vision = /obj/screen/fullscreen/meson


/obj/item/clothing/glasses/meson/prescription
	name = "prescription optical meson scanner"
	desc = "Used for shield the user's eyes from harmful electromagnetic emissions, can also be used as safety googles. Contains prescription lenses."
	prescription = 1

/obj/item/clothing/glasses/meson/yautja
	name = "bio-mask x-ray"
	desc = "A vision overlay generated by the Bio-Mask. Used to see through objects."
	icon = 'icons/obj/items/predator.dmi'
	icon_state = "visor_meson"
	item_state = "securityhud"
	vision_flags = SEE_TURFS
	flags_inventory = COVEREYES
	flags_item = NODROP|DELONDROP

	Dispose()
		..()
		return TA_REVIVE_ME

	Recycle()
		var/blacklist[] = list("icon_state","item_state","name","desc","vision_flags","can_remove")
		. = ..() + blacklist

