#define COLOR_RUTGMC_RED "#B43535"

//Color dedfines used by pill packets
#define COLOR_PACKET_BICARIDINE "#952F48"
#define COLOR_PACKET_KELOTANE "#BD8854"
#define COLOR_PACKET_TRAMADOL "#675772"
#define COLOR_PACKET_TRICORDRAZINE "#FFFFFF"
#define COLOR_PACKET_DYLOVENE "#2DA54B"
#define COLOR_PACKET_PARACETAMOL "#65B4B1"
#define COLOR_PACKET_ISOTONIC "#5c0e0e"
#define COLOR_PACKET_LEPORAZINE "#0066FF"
#define COLOR_PACKET_RUSSIAN_RED "#3d0000"
#define COLOR_PACKET_RYETALYN "#AC6D32"
