//Surplus clothing vendor

/obj/machinery/vending/uniform_supply
	name = "\improper Surplus Clothing Vendor"
	desc = "An automated equipment rack hooked up to a colossal storage of clothing and accessories. Nanotrasen designed a new vendor that utilizes bluespace technology to send surplus equipment from outer colonies' sweatshops to your hands! Be grateful."
	icon_state = "surplus_clothes"
	icon_vend = "surplus_clothes_vend"
	icon_deny = "surplus_clothes_deny"
	wrenchable = FALSE
	isshared = TRUE
	product_ads = "Be the musician that you parents never approve you of.;You gotta look good when you're in the battlefield.;We have all types of hats here!;What did one hat say to the other on the hiking trip? I'll wait here, you go on ahead;Sometimes, a beret is better than a helmet.;Drip is the priority, marine."
	products = list(
		"Standard" = list(
			/obj/item/clothing/under/marine/robotic = -1,
			/obj/item/clothing/under/marine = -1,
			/obj/item/clothing/under/marine/hyperscale = -1,
			/obj/item/clothing/under/marine/camo = -1,
			/obj/item/clothing/under/marine/camo/desert = -1,
			/obj/item/clothing/under/marine/camo/snow = -1,
			/obj/item/clothing/under/marine/orion_fatigue = -1,
			/obj/item/clothing/under/marine/red_fatigue = -1,
			/obj/item/clothing/under/marine/lv_fatigue = -1,
			/obj/item/clothing/under/marine/striped = -1,
			/obj/item/clothing/under/marine/jaeger = -1,
			/obj/item/clothing/under/marine/squad/neck/delta = -1,
			/obj/item/clothing/under/marine/squad/neck/charlie = -1,
			/obj/item/clothing/under/marine/squad/neck/bravo = -1,
			/obj/item/clothing/under/marine/squad/neck/alpha = -1,
			/obj/item/clothing/gloves/marine = -1,
			/obj/item/clothing/gloves/marine/black = -1,
			/obj/item/clothing/gloves/marine/fingerless = -1,
			/obj/item/clothing/gloves/marine/hyperscale = -1,
			/obj/item/clothing/shoes/marine/full = -1,
			/obj/item/clothing/shoes/marine/brown/full = -1,
			/obj/item/clothing/shoes/cowboy = -1,
			/obj/item/armor_module/armor/badge = -1,
			/obj/item/armor_module/armor/cape = -1,
			/obj/item/armor_module/armor/cape/kama = -1,
			/obj/item/armor_module/module/pt_belt = -1,
		),
		"Webbings" = list(
			/obj/item/armor_module/storage/uniform/black_vest = -1,
			/obj/item/armor_module/storage/uniform/brown_vest = -1,
			/obj/item/armor_module/storage/uniform/white_vest = -1,
			/obj/item/armor_module/storage/uniform/webbing = -1,
			/obj/item/armor_module/storage/uniform/holster = -1,
		),
		"Belts" = list(
			/obj/item/storage/belt/marine = -1,
			/obj/item/storage/belt/shotgun = -1,
			/obj/item/storage/belt/shotgun/martini = -1,
			/obj/item/storage/belt/grenade = -1,
			/obj/item/storage/belt/knifepouch = -1,
			/obj/item/belt_harness/marine = -1,
			/obj/item/storage/belt/sparepouch = -1,
			/obj/item/storage/holster/belt/pistol/standard_pistol = -1,
			/obj/item/storage/holster/belt/revolver/standard_revolver = -1,
			/obj/item/storage/holster/t19 = -1,
			/obj/item/storage/holster/blade/machete/full = -1,
			/obj/item/storage/holster/blade/machete/full_harvester = -1,
			/obj/item/storage/belt/utility/full = -1,
			/obj/item/storage/belt/medical_small = -1,
			/obj/item/storage/belt/protein_pack = -1,
		),
		"Pouches" = list(
			/obj/item/storage/pouch/pistol = -1,
			/obj/item/storage/pouch/magazine/large = -1,
			/obj/item/storage/pouch/magazine/pistol/large = -1,
			/obj/item/storage/pouch/shotgun = -1,
			/obj/item/storage/holster/flarepouch/full = -1,
			/obj/item/storage/pouch/grenade = -1,
			/obj/item/storage/pouch/explosive = -1,
			/obj/item/storage/pouch/medkit = -1,
			/obj/item/storage/pouch/medical_injectors = -1,
			/obj/item/storage/pouch/pressurized_reagent_pouch/empty = -1,
			/obj/item/storage/pouch/pressurized_reagent_pouch/bktt = -1,
			/obj/item/storage/pouch/med_lolipops = -1,
			/obj/item/storage/pouch/berrypouch = -1,
			/obj/item/storage/pouch/construction = -1,
			/obj/item/storage/pouch/electronics = -1,
			/obj/item/storage/pouch/tools/full = -1,
			/obj/item/storage/pouch/field_pouch = -1,
			/obj/item/storage/pouch/general/large = -1,
			/obj/item/cell/lasgun/volkite/powerpack/marine = -1,
			/obj/item/storage/pouch/general/medium = -1,
			/obj/item/storage/pouch/protein_pack = -1,
		),
		"Headwear" = list(
			/obj/item/clothing/head/modular/style/beret = -1,
			/obj/item/clothing/head/modular/style/classic_beret = -1,
			/obj/item/clothing/head/modular/style/boonie = -1,
			/obj/item/clothing/head/modular/style/cap = -1,
			/obj/item/clothing/head/modular/style/slouchhat = -1,
			/obj/item/clothing/head/modular/style/ushanka = -1,
			/obj/item/clothing/head/modular/style/campaignhat = -1,
			/obj/item/clothing/head/modular/style/beanie = -1,
			/obj/item/clothing/head/modular/style/headband = -1,
			/obj/item/clothing/head/modular/style/bandana = -1,
		),
		"Masks" = list(
			/obj/item/clothing/mask/rebreather/scarf = -1,
			/obj/item/clothing/mask/bandanna/skull = -1,
			/obj/item/clothing/mask/bandanna/green = -1,
			/obj/item/clothing/mask/bandanna/white = -1,
			/obj/item/clothing/mask/bandanna/black = -1,
			/obj/item/clothing/mask/bandanna = -1,
			/obj/item/clothing/mask/bandanna/alpha = -1,
			/obj/item/clothing/mask/bandanna/bravo = -1,
			/obj/item/clothing/mask/bandanna/charlie = -1,
			/obj/item/clothing/mask/bandanna/delta = -1,
			/obj/item/clothing/mask/rebreather = -1,
			/obj/item/clothing/mask/breath = -1,
			/obj/item/clothing/mask/gas/modular/skimask = -1,
			/obj/item/clothing/mask/gas/modular/coofmask = -1,
			/obj/item/clothing/mask/gas = -1,
			/obj/item/clothing/mask/gas/tactical = -1,
			/obj/item/clothing/mask/gas/tactical/coif = -1,
		),
		"Backpacks" = list(
			/obj/item/storage/backpack/marine/standard = -1,
			/obj/item/storage/backpack/marine/satchel = -1,
			/obj/item/tool/weldpack/marinestandard = -1,
		),
		"Instruments" = list(
			/obj/item/instrument/violin = -1,
			/obj/item/instrument/piano_synth = -1,
			/obj/item/instrument/banjo = -1,
			/obj/item/instrument/guitar = -1,
			/obj/item/instrument/glockenspiel = -1,
			/obj/item/instrument/accordion = -1,
			/obj/item/instrument/trumpet = -1,
			/obj/item/instrument/saxophone = -1,
			/obj/item/instrument/trombone = -1,
			/obj/item/instrument/recorder = -1,
			/obj/item/instrument/harmonica = -1,
		),
		"Dress Uniform" = list(
			/obj/effect/vendor_bundle/white_dress = -1,
			/obj/item/clothing/under/marine/whites = -1,
			/obj/item/clothing/suit/white_dress_jacket = -1,
			/obj/item/clothing/head/white_dress = -1,
			/obj/item/clothing/shoes/white = -1,
			/obj/item/clothing/gloves/white = -1,
			/obj/effect/vendor_bundle/service_uniform = -1,
			/obj/item/clothing/under/marine/service = -1,
			/obj/item/clothing/head/garrisoncap = -1,
			/obj/item/clothing/head/serviceberet = -1,
			/obj/item/clothing/head/servicecampaignhat = -1,
			/obj/item/clothing/head/serviceushanka = -1,
			/obj/item/clothing/head/servicecap = -1,
			/obj/item/clothing/under/marine/black_suit = -1,
		),
		"Surplus Headwear" = list(
			/obj/item/clothing/head/slouch = -1,
			/obj/item/clothing/head/headband/red = -1,
			/obj/item/clothing/head/headband/rambo = -1,
			/obj/item/clothing/head/headband/snake = -1,
			/obj/item/clothing/head/headband = -1,
			/obj/item/clothing/head/bandanna/grey = -1,
			/obj/item/clothing/head/bandanna/brown = -1,
			/obj/item/clothing/head/bandanna/red = -1,
			/obj/item/clothing/head/tgmcberet/tan = -1,
			/obj/item/clothing/head/tgmcberet/red = -1,
			/obj/item/clothing/head/tgmcberet/red2 = -1,
			/obj/item/clothing/head/tgmcberet/blueberet = -1,
			/obj/item/clothing/head/tgmcberet/darkgreen = -1,
			/obj/item/clothing/head/tgmcberet/green = -1,
			/obj/item/clothing/head/tgmcberet/snow = -1,
			/obj/item/clothing/head/beret/marine = -1,
			/obj/item/clothing/head/tgmcberet = -1,
		),
		"Medical Clothing" = list(
			/obj/item/clothing/under/rank/medical/blue = -1,
			/obj/item/clothing/under/rank/medical/green = -1,
			/obj/item/clothing/under/rank/medical/purple = -1,
			/obj/item/clothing/suit/storage/labcoat = -1,
			/obj/item/clothing/suit/surgical = -1,
			/obj/item/clothing/mask/surgical = -1,
			/obj/item/clothing/gloves/latex = -1,
			/obj/item/clothing/shoes/white = -1,
		),
		"Eyewear" = list(
			/obj/item/clothing/glasses/regular = -1,
			/obj/item/clothing/glasses/eyepatch = -1,
			/obj/item/clothing/glasses/sunglasses/fake/big = -1,
			/obj/item/clothing/glasses/sunglasses/fake/big/prescription = -1,
			/obj/item/clothing/glasses/sunglasses/fake = -1,
			/obj/item/clothing/glasses/sunglasses/fake/prescription = -1,
			/obj/item/clothing/glasses/mgoggles = -1,
			/obj/item/clothing/glasses/mgoggles/prescription = -1,
		),
	)

	prices = list()

/obj/machinery/vending/uniform_supply/valhalla
	resistance_flags = INDESTRUCTIBLE
	use_power = NO_POWER_USE
