/obj/machinery/vending/weapon/hvh2

	products = list(
		"Rifles" = list(
			/obj/item/weapon/gun/rifle/standard_assaultrifle = -1,
			/obj/item/ammo_magazine/rifle/standard_assaultrifle = -1,
			/obj/item/weapon/gun/rifle/standard_carbine = -1,
			/obj/item/ammo_magazine/rifle/standard_carbine = -1,
			/obj/item/weapon/gun/rifle/standard_skirmishrifle = -1,
			/obj/item/ammo_magazine/rifle/standard_skirmishrifle = -1,
			/obj/item/weapon/gun/rifle/tx11/scopeless = -1,
			/obj/item/ammo_magazine/rifle/tx11 = -1,
		),
		"Energy Weapons" = list(
			/obj/item/weapon/gun/energy/lasgun/lasrifle/standard_marine_rifle = -1,
			/obj/item/weapon/gun/energy/lasgun/lasrifle/standard_marine_carbine = -1,
			/obj/item/weapon/gun/energy/lasgun/lasrifle/standard_marine_mlaser = -1,
			/obj/item/weapon/gun/energy/lasgun/lasrifle/standard_marine_pistol = -1,
			/obj/item/cell/lasgun/lasrifle = -1,
		),
		"SMGs" = list(
			/obj/item/weapon/gun/smg/standard_smg = -1,
			/obj/item/ammo_magazine/smg/standard_smg = -1,
			/obj/item/weapon/gun/smg/standard_machinepistol = -1,
			/obj/item/ammo_magazine/smg/standard_machinepistol = -1,
			/obj/item/weapon/gun/smg/ppsh = -1,
			/obj/item/ammo_magazine/smg/ppsh = -1,
			/obj/item/ammo_magazine/smg/ppsh/extended = -1,
		),
		"Marksman" = list(
		),
		"Shotgun" = list(
			/obj/item/weapon/gun/shotgun/pump/t35 = -1,
			/obj/item/weapon/gun/shotgun/combat/standardmarine = -1,
			/obj/item/weapon/gun/shotgun/combat = -1,
			/obj/item/weapon/gun/shotgun/pump/cmb = -1,
			/obj/item/weapon/gun/shotgun/double/marine = -1,
			/obj/item/storage/belt/gun/ts34/full = -1,
			/obj/item/ammo_magazine/shotgun/buckshot = -1,
			/obj/item/ammo_magazine/shotgun/flechette = -1,
			/obj/item/weapon/gun/rifle/standard_autoshotgun = -1,
			/obj/item/ammo_magazine/rifle/tx15_flechette = -1,
		),
		"Machinegun" = list(
			/obj/item/weapon/gun/rifle/standard_lmg = -1,
			/obj/item/ammo_magazine/standard_lmg = -1,
			/obj/item/weapon/gun/rifle/standard_gpmg = -1,
			/obj/item/ammo_magazine/standard_gpmg = -1,
			/obj/item/weapon/gun/standard_mmg = 5,
			/obj/item/ammo_magazine/standard_mmg = -1,
		),
		"Sidearm" = list(
			/obj/item/weapon/gun/pistol/standard_pistol = -1,
			/obj/item/ammo_magazine/pistol/standard_pistol = -1,
			/obj/item/weapon/gun/pistol/standard_heavypistol = -1,
			/obj/item/ammo_magazine/pistol/standard_heavypistol = -1,
			/obj/item/weapon/gun/revolver/standard_revolver = -1,
			/obj/item/ammo_magazine/revolver/standard_revolver = -1,
			/obj/item/weapon/gun/pistol/standard_pocketpistol = -1,
			/obj/item/ammo_magazine/pistol/standard_pocketpistol = -1,
			/obj/item/weapon/gun/pistol/vp70 = -1,
			/obj/item/ammo_magazine/pistol/vp70 = -1,
			/obj/item/weapon/gun/pistol/plasma_pistol = -1,
			/obj/item/ammo_magazine/pistol/plasma_pistol = -1,
		),
		"Specialized" = list(
			/obj/item/weapon/gun/grenade_launcher/multinade_launcher = -1,
			/obj/item/weapon/gun/grenade_launcher/single_shot = -1,
			/obj/item/weapon/gun/heavymachinegun = 1,
			/obj/item/ammo_magazine/heavymachinegun = 4,
			/obj/item/storage/box/recoilless_system = 2,
			/obj/item/weapon/gun/flamer/big_flamer/marinestandard = 4,
			/obj/item/ammo_magazine/flamer_tank/backtank = 4,
			/obj/item/ammo_magazine/flamer_tank/large = 20,
			/obj/item/ammo_magazine/flamer_tank = 20,
			/obj/item/weapon/shield/riot/marine = 6,
			/obj/item/jetpack_marine = 3,
			/obj/item/weapon/powerfist = -1,
			/obj/item/stack/throwing_knife = -1,
			/obj/item/weapon/twohanded/spear/tactical = -1,
		),
		"Grenades" = list(
			/obj/item/explosive/grenade = 600,
			/obj/item/explosive/grenade/m15 = 50,
			/obj/item/explosive/grenade/incendiary = 50,
			/obj/item/explosive/grenade/smokebomb = 50,
			/obj/item/explosive/grenade/smokebomb/cloak = 50,
			/obj/item/explosive/grenade/smokebomb/drain = 10,
			/obj/item/explosive/grenade/mirage = 100,
			/obj/item/storage/box/m94 = 200,
			/obj/item/storage/box/m94/cas = 30,
		),
		"Attachments" = list(
			/obj/item/attachable/bayonet = -1,
			/obj/item/attachable/compensator = -1,
			/obj/item/attachable/extended_barrel = -1,
			/obj/item/attachable/lace = -1,
			/obj/item/attachable/flashlight = -1,
			/obj/item/attachable/magnetic_harness = -1,
			/obj/item/attachable/reddot = -1,
			/obj/item/attachable/angledgrip = -1,
			/obj/item/attachable/bipod = -1,
			/obj/item/attachable/burstfire_assembly = -1,
			/obj/item/attachable/gyro = -1,
			/obj/item/attachable/lasersight = -1,
			/obj/item/attachable/verticalgrip = -1,
			/obj/item/attachable/stock/t19stock = -1,
			/obj/item/attachable/stock/t35stock = -1,
			/obj/item/attachable/flamer_nozzle = -1,
			/obj/item/attachable/flamer_nozzle/wide = -1,
			/obj/item/weapon/gun/flamer/mini_flamer = -1,
			/obj/item/ammo_magazine/flamer_tank/mini = -1,
			/obj/item/weapon/gun/grenade_launcher/underslung = -1,
			/obj/item/attachable/motiondetector = -1,

		),
		"Boxes" = list(
			/obj/item/ammo_magazine/packet/p9mm = 100,
			/obj/item/ammo_magazine/packet/acp = 100,
			/obj/item/ammo_magazine/packet/magnum = 100,
			/obj/item/ammo_magazine/packet/p10x24mm = 100,
			/obj/item/ammo_magazine/packet/p10x26mm = 100,
			/obj/item/ammo_magazine/packet/p10x27mm = 100,
			/obj/item/ammo_magazine/packet/p492x34mm = 100,
			/obj/item/ammo_magazine/packet/p4570 = 100,
			/obj/item/storage/box/visual/magazine = 30,
			/obj/item/storage/box/visual/grenade = 10,
		),
		"Utility" = list(
			/obj/item/flashlight/combat = -1,
			/obj/item/weapon/gun/grenade_launcher/single_shot/flare/marine = -1,
			/obj/item/weapon/combat_knife = -1,
			/obj/item/attachable/bayonetknife = -1,
			/obj/item/tool/shovel/etool = -1,
			/obj/item/tool/extinguisher = -1,
			/obj/item/tool/extinguisher/mini = -1,
			/obj/item/assembly/signaler = -1,
			/obj/item/binoculars = -1,
			/obj/item/compass = -1,
		),
	)

/obj/machinery/vending/weapon/hvh2/team_one2

/obj/machinery/vending/weapon/hvh2/team_two2