compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

pnpEnableEsmLoader: false

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
