/datum/game_mode/infestation/extended_plus/extended_mini
	name = "Extended Mini"
	config_tag = "Extended Mini"
	silo_scaling = 1
	round_type_flags = MODE_INFESTATION|MODE_PSY_POINTS|MODE_PSY_POINTS_ADVANCED|MODE_HIJACK_POSSIBLE|MODE_SILO_RESPAWN|MODE_ALLOW_XENO_QUICKBUILD
	shutters_drop_time = 3 MINUTES
	xeno_abilities_flags = ABILITY_NUCLEARWAR
	factions = list(FACTION_TERRAGOV, FACTION_XENO)
	human_factions = list(FACTION_TERRAGOV)
	valid_job_types = list(
		/datum/job/terragov/command/captain = 1,
		/datum/job/terragov/command/fieldcommander = 1,
		/datum/job/terragov/command/corpseccommander = 1,
		/datum/job/terragov/command/staffofficer = 2,
		/datum/job/terragov/command/vanguard = 2,
		/datum/job/terragov/command/pilot = 2,
		/datum/job/terragov/command/transportofficer = 2,
		/datum/job/terragov/command/transport_crewman = 3,
		/datum/job/terragov/command/mech_pilot = 1,
		/datum/job/terragov/engineering/chief = 1,
		/datum/job/terragov/engineering/tech = 2,
		/datum/job/terragov/requisitions/officer = 2,
		/datum/job/terragov/medical/professor = 1,
		/datum/job/terragov/medical/medicalofficer = 3,
		/datum/job/terragov/security/security_officer = 3,
		/datum/job/terragov/medical/researcher = 1,
		/datum/job/terragov/civilian/liaison = 1,
		/datum/job/terragov/silicon/synthetic = 4,
		/datum/job/terragov/silicon/ai = 1,
		/datum/job/terragov/squad/engineer = 4,
		/datum/job/terragov/squad/corpsman = 4,
		/datum/job/terragov/squad/smartgunner = 2,
		/datum/job/terragov/squad/leader = 2,
		/datum/job/terragov/squad/specialist = 2,
		/datum/job/terragov/squad/standard = -1,
		/datum/job/terragov/squad/slut = -1,
		/datum/job/moraleofficer = -1,
		/datum/job/worker = -1,
		/datum/job/other/prisoner = 4,
		/datum/job/xenomorph = 8,
		/datum/job/xenomorph/queen = 1,
	)
	enable_fun_tads = TRUE
	xenorespawn_time = 2 MINUTES
	respawn_time = 5 MINUTES
	bioscan_interval = 30 MINUTES
	deploy_time_lock = 15 SECONDS
