/datum/unit_test/spawn_gun/Run()
	for(var/gun_to_test in subtypesof(/obj/item/weapon/gun))
		var/obj/item/weapon/gun/gun = allocate(gun_to_test, TRUE)
		for(var/attachment_type in gun.starting_attachment_types)
			if(!(attachment_type in gun.attachable_allowed))
				Fail("[attachment_type] is specified as a starting attachment, however it is not an allowed attachment. Called from [gun].")
		if(gun.default_ammo_type && !(gun.default_ammo_type in gun.allowed_ammo_types))
			Fail("[gun] has a specified default_ammo_type that is not present in the allowed_ammo_types.")
		for(var/allowed_ammo_type in gun.allowed_ammo_types)
			gun.reload(new allowed_ammo_type())
			gun.update_ammo_count()
			gun.get_ammo()
			gun.unload()