/obj/machinery/vending
	vend_delay = 10

/obj/machinery/vending/weapon/Initialize(mapload, ...)
	//Really unsafe, but it works
	products["Marksman"] += list(
		/obj/item/weapon/gun/revolver/standard_revolver/coltrifle = -1,
		/obj/item/ammo_magazine/revolver/rifle = -1,
	)
	products["Boxes"] += list(
		/obj/item/ammo_magazine/packet/long_special = -1,
	)
	return ..()

/obj/machinery/vending/armor_supply
	products = list(
		"Xenonauten" = list(
			/obj/item/clothing/suit/modular/xenonauten/light = -1,
			/obj/item/clothing/suit/modular/xenonauten = -1,
			/obj/item/clothing/suit/modular/xenonauten/heavy = -1,
			/obj/item/clothing/head/modular/m10x = -1,
			/obj/item/clothing/head/modular/m10x/heavy = -1,
			/obj/item/clothing/suit/modular/xenonauten/light/mk1 = -1,
			/obj/item/clothing/suit/modular/xenonauten/mk1 = -1,
			/obj/item/clothing/suit/modular/xenonauten/heavy/mk1 = -1,
			/obj/item/clothing/head/modular/m10x/mk1 = -1,
		),
		"Jaeger" = list(
			/obj/item/clothing/suit/modular/jaeger/light = -1,
			/obj/item/clothing/suit/modular/jaeger/light/skirmisher = -1,
			/obj/item/clothing/suit/modular/jaeger = -1,
			/obj/item/clothing/suit/modular/jaeger/eva = -1,
			/obj/item/clothing/suit/modular/jaeger/helljumper = -1,
			/obj/item/clothing/suit/modular/jaeger/ranger = -1,
			/obj/item/clothing/suit/modular/jaeger/heavy = -1,
			/obj/item/clothing/suit/modular/jaeger/heavy/assault = -1,
			/obj/item/clothing/suit/modular/jaeger/heavy/eod = -1,
			/obj/item/clothing/head/modular/marine/skirmisher = -1,
			/obj/item/clothing/head/modular/marine/scout = -1,
			/obj/item/clothing/head/modular/marine = -1,
			/obj/item/clothing/head/modular/marine/eva = -1,
			/obj/item/clothing/head/modular/marine/eva/skull = -1,
			/obj/item/clothing/head/modular/marine/helljumper = -1,
			/obj/item/clothing/head/modular/marine/ranger = -1,
			/obj/item/clothing/head/modular/marine/traditional = -1,
			/obj/item/clothing/head/modular/marine/gungnir = -1,
			/obj/item/clothing/head/modular/marine/assault = -1,
			/obj/item/clothing/head/modular/marine/eod = -1,
		),
		"Combat Robot" = list(
			/obj/item/clothing/suit/modular/robot/light = -1,
			/obj/item/clothing/suit/modular/robot = -1,
			/obj/item/clothing/suit/modular/robot/heavy = -1,
			/obj/item/clothing/head/modular/robot/light = -1,
			/obj/item/clothing/head/modular/robot = -1,
			/obj/item/clothing/head/modular/robot/heavy = -1,
		),
		"General" = list(
			/obj/item/clothing/suit/modular = -1,
			/obj/item/clothing/suit/modular/rownin = -1,
			/obj/item/clothing/suit/modular/xenonauten/pilot = -1,
			/obj/item/facepaint/green = -1,
			/obj/item/facepaint/sniper = -1,
			/obj/item/facepaint/black = -1,
			/obj/item/facepaint/brown = -1,
		),
		"Armor modules" = list(
			/obj/item/armor_module/storage/general = -1,
			/obj/item/armor_module/storage/engineering = -1,
			/obj/item/armor_module/storage/medical = -1,
			/obj/item/armor_module/storage/injector = -1,
			/obj/item/armor_module/storage/grenade = -1,
			/obj/item/armor_module/module/welding = -1,
			/obj/item/armor_module/module/binoculars = -1,
			/obj/item/armor_module/module/artemis = -1,
			/obj/item/armor_module/module/tyr_head = -1,
			/obj/item/armor_module/module/antenna = -1,
			/obj/item/armor_module/module/motion_detector = -1,
			/obj/item/armor_module/module/mimir_environment_protection/mark1 = -1,
			/obj/item/armor_module/module/mimir_environment_protection/mimir_helmet/mark1 = -1,
			/obj/item/armor_module/module/tyr_extra_armor/mark1 = -1,
			/obj/item/armor_module/module/ballistic_armor = -1,
			/obj/item/armor_module/module/hod_head = -1,
			/obj/item/armor_module/module/better_shoulder_lamp = -1,
			/obj/item/armor_module/module/chemsystem = -1,
			/obj/item/armor_module/module/eshield = -1,
		),
		"Jaeger Mk.I chestpieces" = list(
			/obj/item/armor_module/armor/chest/marine/skirmisher = -1,
			/obj/item/armor_module/armor/chest/marine/skirmisher/scout = -1,
			/obj/item/armor_module/armor/chest/marine = -1,
			/obj/item/armor_module/armor/chest/marine/eva = -1,
			/obj/item/armor_module/armor/chest/marine/assault = -1,
			/obj/item/armor_module/armor/chest/marine/assault/eod = -1,
			/obj/item/armor_module/armor/chest/marine/helljumper = -1,
			/obj/item/armor_module/armor/chest/marine/ranger = -1,
		),
		"Jaeger Mk.I armpiece" = list(
			/obj/item/armor_module/armor/arms/marine/skirmisher = -1,
			/obj/item/armor_module/armor/arms/marine/scout = -1,
			/obj/item/armor_module/armor/arms/marine = -1,
			/obj/item/armor_module/armor/arms/marine/eva = -1,
			/obj/item/armor_module/armor/arms/marine/assault = -1,
			/obj/item/armor_module/armor/arms/marine/eod = -1,
			/obj/item/armor_module/armor/arms/marine/helljumper = -1,
			/obj/item/armor_module/armor/arms/marine/ranger = -1,
		),
		"Jaeger Mk.I legpiece" = list(
			/obj/item/armor_module/armor/legs/marine/skirmisher = -1,
			/obj/item/armor_module/armor/legs/marine/scout = -1,
			/obj/item/armor_module/armor/legs/marine = -1,
			/obj/item/armor_module/armor/legs/marine/eva = -1,
			/obj/item/armor_module/armor/legs/marine/assault = -1,
			/obj/item/armor_module/armor/legs/marine/eod = -1,
			/obj/item/armor_module/armor/legs/marine/scout = -1,
			/obj/item/armor_module/armor/legs/marine/helljumper = -1,
			/obj/item/armor_module/armor/legs/marine/ranger = -1,
		),
		"Jaeger Mk.I helmets" = list(
			/obj/item/clothing/head/modular/marine/old/skirmisher = -1,
			/obj/item/clothing/head/modular/marine/old/scout = -1,
			/obj/item/clothing/head/modular/marine/old = -1,
			/obj/item/clothing/head/modular/marine/old/open = -1,
			/obj/item/clothing/head/modular/marine/old/eva = -1,
			/obj/item/clothing/head/modular/marine/old/eva/skull = -1,
			/obj/item/clothing/head/modular/marine/old/assault = -1,
			/obj/item/clothing/head/modular/marine/old/eod = -1,
		),
	)

/obj/machinery/vending/uniform_supply
	products = list(
		"Standard" = list(
			/obj/item/clothing/under/marine/robotic = -1,
			/obj/item/clothing/under/marine = -1,
			/obj/item/clothing/under/marine/camo = -1,
			/obj/item/clothing/under/marine/camo/desert = -1,
			/obj/item/clothing/under/marine/camo/snow = -1,
			/obj/item/clothing/under/marine/orion_fatigue = -1,
			/obj/item/clothing/under/marine/red_fatigue = -1,
			/obj/item/clothing/under/marine/lv_fatigue = -1,
			/obj/item/clothing/under/marine/striped = -1,
			/obj/item/clothing/under/marine/jaeger = -1,
			/obj/item/clothing/under/marine/squad/neck/delta = -1,
			/obj/item/clothing/under/marine/squad/neck/charile = -1,
			/obj/item/clothing/under/marine/squad/neck/bravo = -1,
			/obj/item/clothing/under/marine/squad/neck/alpha = -1,
			/obj/item/clothing/under/marine/squad/neck/foreign = -1,
			/obj/item/clothing/gloves/marine/black = -1,
			/obj/item/clothing/gloves/marine/fingerless = -1,
			/obj/item/clothing/shoes/marine/full = -1,
			/obj/item/clothing/shoes/marine/brown/full = -1,
			/obj/item/clothing/shoes/cowboy = -1,
			/obj/item/armor_module/armor/badge = -1,
			/obj/item/armor_module/armor/cape/kama = -1,
			/obj/item/armor_module/module/pt_belt = -1,
		),
		"Webbings" = list(
			/obj/item/armor_module/storage/uniform/black_vest = -1,
			/obj/item/armor_module/storage/uniform/brown_vest = -1,
			/obj/item/armor_module/storage/uniform/white_vest = -1,
			/obj/item/armor_module/storage/uniform/webbing = -1,
			/obj/item/armor_module/storage/uniform/holster = -1,
		),
		"Belts" = list(
			/obj/item/storage/belt/marine = -1,
			/obj/item/storage/belt/shotgun = -1,
			/obj/item/storage/belt/shotgun/martini = -1,
			/obj/item/storage/belt/grenade = -1,
			/obj/item/belt_harness/marine = -1,
			/obj/item/storage/belt/sparepouch = -1,
			/obj/item/storage/holster/belt/pistol/standard_pistol = -1,
			/obj/item/storage/holster/belt/revolver/standard_revolver = -1,
			/obj/item/storage/holster/t19 = -1,
			/obj/item/storage/holster/blade/machete/full = -1,
			/obj/item/storage/holster/blade/machete/full_harvester = -1,
			/obj/item/weapon/twohanded/glaive/harvester = -1,
			/obj/item/storage/belt/utility/full =-1,
			/obj/item/storage/belt/medical_small = -1,
		),
		"Pouches" = list(
			/obj/item/storage/pouch/pistol = -1,
			/obj/item/storage/pouch/magazine/large = -1,
			/obj/item/storage/pouch/magazine/pistol/large = -1,
			/obj/item/storage/pouch/shotgun = -1,
			/obj/item/storage/holster/flarepouch/full = -1,
			/obj/item/storage/pouch/grenade = -1,
			/obj/item/storage/pouch/explosive = -1,
			/obj/item/storage/pouch/medkit = -1,
			/obj/item/storage/pouch/medical_injectors = -1,
			/obj/item/storage/pouch/med_lolipops = -1,
			/obj/item/storage/pouch/construction = -1,
			/obj/item/storage/pouch/electronics = -1,
			/obj/item/storage/pouch/tools/full = -1,
			/obj/item/storage/pouch/field_pouch = -1,
			/obj/item/storage/pouch/general/large = -1,
			/obj/item/cell/lasgun/volkite/powerpack/marine = -1,
			/obj/item/storage/pouch/general/medium = -1,
		),
		"Headwear" = list(
			/obj/item/clothing/head/slouch = -1,
			/obj/item/clothing/head/headband/red = -1,
			/obj/item/clothing/head/headband/rambo = -1,
			/obj/item/clothing/head/headband/snake = -1,
			/obj/item/clothing/head/headband = -1,
			/obj/item/clothing/head/squadhb = -1,
			/obj/item/clothing/head/squadhb/b = -1,
			/obj/item/clothing/head/squadhb/c = -1,
			/obj/item/clothing/head/squadhb/d = -1,
			/obj/item/clothing/head/squadhb/fl = -1,
			/obj/item/clothing/head/bandanna/grey = -1,
			/obj/item/clothing/head/bandanna/brown = -1,
			/obj/item/clothing/head/bandanna/red = -1,
			/obj/item/clothing/head/tgmcberet/tan = -1,
			/obj/item/clothing/head/tgmcberet/red = -1,
			/obj/item/clothing/head/tgmcberet/red2 = -1,
			/obj/item/clothing/head/tgmcberet/blueberet = -1,
			/obj/item/clothing/head/tgmcberet/darkgreen = -1,
			/obj/item/clothing/head/tgmcberet/green = -1,
			/obj/item/clothing/head/tgmcberet/snow = -1,
			/obj/item/clothing/head/tgmcberet/squad/alpha = -1,
			/obj/item/clothing/head/tgmcberet/squad/bravo = -1,
			/obj/item/clothing/head/tgmcberet/squad = -1,
			/obj/item/clothing/head/tgmcberet/squad/delta = -1,
			/obj/item/clothing/head/tgmcberet/squad/foreign = -1,
			/obj/item/clothing/head/tgmcberet/vdv = -1,
			/obj/item/clothing/head/tgmcberet/commando = -1,
			/obj/item/clothing/head/beret/marine = -1,
			/obj/item/clothing/head/tgmcberet = -1,
			/obj/item/clothing/glasses/mgoggles = -1,
			/obj/item/clothing/glasses/mgoggles/prescription = -1,
		),
		"Masks" = list(
			/obj/item/clothing/mask/rebreather/scarf = -1,
			/obj/item/clothing/mask/bandanna/skull = -1,
			/obj/item/clothing/mask/bandanna/green = -1,
			/obj/item/clothing/mask/bandanna/white = -1,
			/obj/item/clothing/mask/bandanna/black = -1,
			/obj/item/clothing/mask/bandanna = -1,
			/obj/item/clothing/mask/bandanna/alpha = -1,
			/obj/item/clothing/mask/bandanna/bravo = -1,
			/obj/item/clothing/mask/bandanna/charlie = -1,
			/obj/item/clothing/mask/bandanna/delta = -1,
			/obj/item/clothing/mask/balaclava = -1,
			/obj/item/clothing/mask/rebreather = -1,
			/obj/item/clothing/mask/breath = -1,
			/obj/item/clothing/mask/gas = -1,
			/obj/item/clothing/mask/gas/tactical = -1,
			/obj/item/clothing/mask/gas/tactical/coif = -1,
		),
		"Backpacks" = list(
			/obj/item/storage/backpack/marine/standard = -1,
			/obj/item/storage/backpack/marine/satchel = -1,
			/obj/item/storage/backpack/marine/satchel/green = -1,
			/obj/item/storage/backpack/marine/standard/molle = -1,
			/obj/item/storage/backpack/marine/satchel/molle = -1,
			/obj/item/tool/weldpack/marinestandard = -1,
		),
		"Instruments" = list(
			/obj/item/instrument/violin = -1,
			/obj/item/instrument/piano_synth = -1,
			/obj/item/instrument/banjo = -1,
			/obj/item/instrument/guitar = -1,
			/obj/item/instrument/glockenspiel = -1,
			/obj/item/instrument/accordion = -1,
			/obj/item/instrument/trumpet = -1,
			/obj/item/instrument/saxophone = -1,
			/obj/item/instrument/trombone = -1,
			/obj/item/instrument/recorder = -1,
			/obj/item/instrument/harmonica = -1,
		),
		"Dress Uniform" = list(
			/obj/effect/vendor_bundle/white_dress = -1,
			/obj/item/clothing/under/marine/whites = -1,
			/obj/item/clothing/suit/white_dress_jacket = -1,
			/obj/item/clothing/head/white_dress = -1,
			/obj/item/clothing/shoes/white = -1,
			/obj/item/clothing/gloves/white = -1,
			/obj/effect/vendor_bundle/service_uniform = -1,
			/obj/item/clothing/under/marine/service = -1,
			/obj/item/clothing/head/garrisoncap = -1,
			/obj/item/clothing/head/serviceberet = -1,
			/obj/item/clothing/head/servicecap = -1,
		),
	)

/obj/machinery/vending/medical_uniform_supply
	name = "\improper Medical Clothing Vendor"
	desc = "A special medical vendor designed to supply you with various blood absorbing clothing!"
	icon = 'modular_RUtgmc/icons/obj/machines/vending.dmi'
	icon_state = "medidrobe"
	icon_vend = "medidrobe-vend"
	icon_deny = "medidrobe-deny"
	req_access = list(ACCESS_MARINE_MEDBAY, ACCESS_MARINE_CHEMISTRY) //only doctors and researchers can access these
	isshared = TRUE
	product_ads = "If they aren't bleeding, check again."
	products = list(
		"Medical Clothing" = list(
			/obj/item/clothing/under/rank/medical/blue = 3,
			/obj/item/clothing/under/rank/medical/green = 3,
			/obj/item/clothing/under/rank/medical/purple = 3,
			/obj/item/clothing/suit/storage/labcoat = 3,
			/obj/item/clothing/suit/surgical = 3,
			/obj/item/clothing/mask/surgical = 3,
			/obj/item/clothing/head/tgmcberet/medical = 3,
			/obj/item/storage/backpack/satchel/med = 3,
			/obj/item/clothing/gloves/latex = -1,
			/obj/item/clothing/shoes/white = -1,
		),
	)
