/mob/living/simple_animal/shade
	name = "Shade"
	real_name = "Shade"
	desc = "A bound spirit."
	gender = PLURAL
	icon = 'icons/mob/mob.dmi'
	icon_state = "shade"
	icon_living = "shade"
	maxHealth = 40
	health = 40
	healable = 0
	speak_emote = list("hisses")
	emote_hear = list("wails.","screeches.")
	response_help = "puts their hand through"
	response_disarm = "flails at"
	response_harm = "punches"
	speak_chance = 1
	melee_damage = 12
	attacktext = "metaphysically strikes"
	stop_automated_movement = TRUE
	flags_status = NONE
	faction = list("cult")
	flags_status = CANPUSH
	del_on_death = TRUE
