/mob/living/simple_animal/lizard
	name = "Lizard"
	desc = "A cute tiny lizard."
	icon_state = "lizard"
	icon_living = "lizard"
	icon_dead = "lizard_dead"
	speak_emote = list("hisses")
	health = 5
	maxHealth = 5
	faction = list("Lizard")
	attacktext = "bites"
	melee_damage = 1
	response_help = "pets"
	response_disarm = "shoos"
	response_harm = "stomps on"
	density = FALSE
	allow_pass_flags = PASS_MOB
	pass_flags = PASS_LOW_STRUCTURE|PASS_MOB
	mob_size = MOB_SIZE_SMALL
	obj_damage = 0
