name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tgstation/tgstation
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest"
          cache: true
