name: "Round ID Linker"
on:
  issues:
    types: [opened]

jobs:
  link_rounds:
    runs-on: ubuntu-20.04
    steps:
    - uses: tgstation/round_linker@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
