name: Automatic Approve Workflows
on:
  schedule: 
    - cron: "*/10 * * * *"
jobs:
  automatic-approve:
    name: Automatic Approve Workflows
    runs-on: ubuntu-20.04
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflows: "ci_suite.yml"
          dangerous_files: "build.bat"
